CREATE PROCEDURE [dbo].[DELETE_MST_DIAGNOSIS_CODE]
@DomainId NVARCHAR(50),
@SZ_DIAGNOSIS_CODE_ID		INT=NULL


AS
BEGIN

		DELETE FROM  MST_DIAGNOSIS_CODE
		WHERE SZ_DIAGNOSIS_CODE_ID=@SZ_DIAGNOSIS_CODE_ID
		AND DomainId=@DomainId
END

