CREATE PROCEDURE [dbo].[F_DDL_TEMPLATES_BYUSERID]

	@s_a_Value NVARCHAR(100)
AS
BEGIN
	SELECT 
		T.I_TEMPLATE_ID,T.SZ_TEMPLATE_NAME 
	FROM 
		MST_LATEST T
		INNER JOIN
		TXN_TEMPLATES_ACCESS A
		ON T.I_LATE_ID = A.TEMPLATE_ID
	WHERE
		USER_TYPE = @s_a_Value
	order by SZ_LATE_NAME 
END

