
CREATE PROCEDURE [dbo].[GET_ALL_TEMPLATES]--[GET_ALL_TEMPLATES] 'test2'
	@DomainId varchar(50)
AS
BEGIN

	SELECT m.I_TEMPLATE_ID [TEMPLATE_ID], m.SZ_TEMPLATE_NAME [TEMPLATE_NAME], m.SZ_TEMPLATE_FILENAME [TEMPLATE_FILE_NAME]
	FROM MST_TEMPLATES  m 
	WHERE m.DomainId = @DomainId

END

