CREATE PROCEDURE [dbo].[GET_INSERT_CASE_ASSIGNMENT_FOLDER] --'FH11-80531',null,'GET'
	@DomainId NVARCHAR(50),
	@CASE_ID VARCHAR(100),
	@FOLDER_PATH VARCHAR(MAX)=NULL,
	@FLAG VARCHAR(100)
AS
BEGIN
	IF @FLAG = 'GET'
	BEGIN
		SELECT GBDOCUMENT_RELATIVEPATH
		FROM tblcase 
		WHERE CASE_ID = @CASE_ID
		AND DomainId=@DomainId
	END
	IF @FLAG = 'INSERT'
	BEGIN
		UPDATE tblcase 
		SET GBDOCUMENT_RELATIVEPATH = @FOLDER_PATH,
		GBDOCUMENT_ABSOLUTEPATH = @FOLDER_PATH	
		WHERE CASE_ID = @CASE_ID
		AND DomainId=@DomainId
	END
END

