CREATE PROCEDURE [dbo].[GET_TEMPLATES_BY ID]
	@DomainId nvarchar(50),
	@templateid int
AS
BEGIN
	SELECT 
		I_TEMPLATE_ID [TEMPLATE_ID],
		SZ_TEMPLATE_NAME [TEMPLATE_NAME],
		SZ_TEMPLATE_FILENAME [TEMPLATE_FILE_NAME]
	FROM  
		MST_TEMPLATES 
	where I_TEMPLATE_ID = @templateid
	AND DomainId=@DomainId
END

