CREATE PROCEDURE [dbo].[GETPROVIDERS_SETTLEDANDPAID] --'0','1993','01/01/2008','01/01/2011','',''
(
	@SZ_INSURANCE_ID VARCHAR(255),
	@SZ_PROVIDER_ID VARCHAR(255),
	@SZ_START_DATE VARCHAR(50),
	@SZ_END_DATE VARCHAR(10),
	@PROVIDER_GROUP VARCHAR(10),
	@INSURANCE_GROUP VARCHAR(10)
)
AS
BEGIN

	DECLARE @STRQUERY VARCHAR(MAX)
	DECLARE @STRGROUP VARCHAR(MAX)
	DECLARE @STRWHERE VARCHAR(MAX)

	SET @STRQUERY = 'SELECT 
			YEAR(SETTLEMENT_DATE) AS YEARSET,
			COUNT(DISTINCT C.CASE_ID) AS NOOFCASES,
			AVG(DATEDIFF(D,SETTLEMENT_DATE,T.TRANSACTIONS_DATE)) AS AVGDAYSSETTLEDPAID 
		FROM 
			TBLCASE C WITH(NOLOCK)
			INNER JOIN  dbo.tblInsuranceCompany WITH (NOLOCK) ON C.InsuranceCompany_Id = dbo.tblInsuranceCompany.InsuranceCompany_Id   
            INNER JOIN dbo.tblProvider WITH (NOLOCK) ON C.Provider_Id = dbo.tblProvider.Provider_Id   
			LEFT OUTER JOIN  dbo.tblSettlements WITH (NOLOCK) ON C.Case_Id = dbo.tblSettlements.Case_Id  
			INNER JOIN TBLTRANSACTIONS T WITH (NOLOCK) ON C.CASE_ID=T.CASE_ID 
		WHERE ISNULL(C.IsDeleted,0) = 0   AND
			T.TRANSACTIONS_TYPE=''C'' 
			AND SETTLEMENT_DATE IS NOT NULL 
			AND T.TRANSACTIONS_DATE IS NOT NULL '

	IF @PROVIDER_GROUP = '1' AND @PROVIDER_GROUP <> 'ALL'
	BEGIN
		SET @STRWHERE  = ' AND PROVIDER_GROUPNAME IN (SELECT PROVIDER_GROUPNAME FROM TBLPROVIDER WHERE PROVIDER_ID =  ' + @SZ_PROVIDER_ID + ') '
	END
	ELSE IF @SZ_PROVIDER_ID <> 'ALL'
	BEGIN
		SET @STRWHERE  = ' AND C.PROVIDER_ID =  ''' + @SZ_PROVIDER_ID + ''''
	END
	IF @INSURANCE_GROUP  = '1' AND @INSURANCE_GROUP <> 'ALL'
	BEGIN
		SET @STRWHERE  = @STRWHERE +  ' AND INSURANCECOMPANY_GROUPNAME IN (SELECT INSURANCECOMPANY_GROUPNAME FROM TBLINSURANCECOMPANY WHERE INSURANCECOMPANY_ID =  ' 
		+ @SZ_INSURANCE_ID  + ') '
	END
	ELSE IF @SZ_INSURANCE_ID <> '0'
	BEGIN
		SET @STRWHERE  = @STRWHERE + ' AND C.INSURANCECOMPANY_ID =  ' + @SZ_INSURANCE_ID
	END

	SET @STRWHERE = @STRWHERE + ' AND
			CAST(FLOOR(CAST(DATE_OPENED AS FLOAT))AS DATETIME) >= REPLACE(''' + @SZ_START_DATE + ''',''/'',''-'') 
			AND  
			CAST(FLOOR(CAST(DATE_OPENED AS FLOAT))AS DATETIME) <= REPLACE(''' + @SZ_END_DATE + ''',''/'',''-'')'



	SET @STRGROUP = ' GROUP BY YEAR(SETTLEMENT_DATE) ORDER BY YEAR(SETTLEMENT_DATE)'

	PRINT(@STRQUERY + @STRWHERE + @STRGROUP)
	EXEC(@STRQUERY + @STRWHERE + @STRGROUP)

END

