CREATE PROCEDURE [dbo].[GETPROVIDERS_SPECIALITY] --'',''
	@USERTYPE NVARCHAR(50),
	@USERTYPELOGIN NVARCHAR(50)
AS
BEGIN
	SELECT 
		SERVICETYPE AS CODE,
		SERVICETYPE AS [DESC]
	FROM
		TBLSERVICETYPE
	ORDER BY SERVICETYPE
END

