CREATE PROCEDURE [dbo].[INSERT_TXN_SET_ORDER]
	@DomainId NVARCHAR(50),
	@IMAGEID VARCHAR(500)
AS
BEGIN

	DECLARE @BASEFOLDER AS VARCHAR(5000)
	DECLARE @SZ_FILENAME AS VARCHAR(1000)
	DECLARE @SZ_FILEPATH AS VARCHAR(MAX)
	DECLARE @SEQ_ORDER AS INT

	SELECT @BASEFOLDER=PARAMETERVALUE FROM tblApplicationSettings WHERE PARAMETERNAME='DocumentUploadLocationPhysical' and DomainId=@DomainId
	SELECT @SZ_FILENAME = FILENAME FROM TBLDOCIMAGES WHERE IMAGEID = @IMAGEID and DomainId=@DomainId
	SELECT @SZ_FILEPATH = @BASEFOLDER + @DomainId+'/' + FILEPATH + FILENAME FROM TBLDOCIMAGES WHERE IMAGEID=@IMAGEID and DomainId=@DomainId

	SET @SEQ_ORDER = (SELECT ISNULL(MAX(SEQ_ORDER + 1),1) FROM TXN_SET_ORDER WHERe DomainId = @DomainId)
	
	INSERT INTO TXN_SET_ORDER
	(
		SZ_IMAGEID,
		SZ_FILENAME,
		SZ_FILEPATH,
		SEQ_ORDER,
		DomainId
	)
	VALUES
	(
		@IMAGEID,
		@SZ_FILENAME,
		@SZ_FILEPATH,
		@SEQ_ORDER,
		@DomainId
	)
END

