CREATE PROCEDURE [dbo].[LCJ_FREEZETRANSACTIONS](        
@DomainId NVARCHAR(50),
@Provider_Id varchar(50)        
)        
as        
BEGIN        
DECLARE        
@IID INT ,
@BILL_FF INT,
@RETURN_FF INT,
@RETURN_RFB INT      
SET @IID = 0        
SELECT @IID = MAX(ACCOUNT_ID) FROM TBLCLIENTACCOUNT WHERE PROVIDER_ID=@Provider_Id  AND DATEDIFF(D,ACCOUNT_DATE,GETDATE())=0 and DomainId=@DomainId



IF @IID > 0    
BEGIN 
	
  
		UPDATE TBLTRANSACTIONS SET TRANSACTIONS_STATUS='FREEZED',INVOICE_ID=@IID WHERE PROVIDER_ID=@PROVIDER_ID AND (TRANSACTIONS_STATUS IS NULL or TRANSACTIONS_STATUS = 'CONFIRMED') AND TRANSACTIONS_TYPE IN ('C','I') AND (Provider_Id IN (SELECT Provider_Id FROM tblProviderFinancial WHERE DomainId=@DomainId)) 
		
		UPDATE TBLTRANSACTIONS SET TRANSACTIONS_STATUS='FREEZED',INVOICE_ID=@IID WHERE PROVIDER_ID=@PROVIDER_ID AND (TRANSACTIONS_STATUS IS NULL or TRANSACTIONS_STATUS = 'CONFIRMED') AND TRANSACTIONS_TYPE IN ('C','I','Prec','PreCToP') AND (Provider_Id NOT IN (SELECT Provider_Id FROM tblProviderFinancial WHERE DomainId=@DomainId))
		
		SELECT @BILL_FF = ISNULL(PROVIDER_FF,0) FROM TBLPROVIDER WHERE PROVIDER_ID=@PROVIDER_ID and DomainId=@DomainId
		
		IF @BILL_FF=1
			UPDATE TBLTRANSACTIONS SET TRANSACTIONS_STATUS='FREEZED',INVOICE_ID=@IID WHERE PROVIDER_ID=@PROVIDER_ID AND (TRANSACTIONS_STATUS IS NULL or TRANSACTIONS_STATUS = 'CONFIRMED') AND TRANSACTIONS_TYPE IN ('EXP','FFB') and DomainId=@DomainId
		ELSE
			UPDATE TBLTRANSACTIONS SET TRANSACTIONS_STATUS='FREEZED',INVOICE_ID=@IID WHERE PROVIDER_ID=@PROVIDER_ID AND (TRANSACTIONS_STATUS IS NULL or TRANSACTIONS_STATUS = 'CONFIRMED') AND TRANSACTIONS_TYPE IN ('EXP') and DomainId=@DomainId
		
		
		SELECT @RETURN_FF = ISNULL(PROVIDER_RETURNFF,0) FROM TBLPROVIDER WHERE PROVIDER_ID=@PROVIDER_ID and DomainId=@DomainId
		SELECT @RETURN_RFB = ISNULL(Provider_Rebuttal,0) FROM TBLPROVIDER WHERE PROVIDER_ID=@PROVIDER_ID and DomainId=@DomainId
		
		
		
		IF @RETURN_FF=1
			UPDATE TBLTRANSACTIONS SET TRANSACTIONS_STATUS='FREEZED',INVOICE_ID=@IID WHERE PROVIDER_ID=@PROVIDER_ID AND (TRANSACTIONS_STATUS IS NULL or TRANSACTIONS_STATUS = 'CONFIRMED') AND TRANSACTIONS_TYPE IN ('FFC') and DomainId=@DomainId
		
		IF @RETURN_RFB = 1
					UPDATE TBLTRANSACTIONS SET TRANSACTIONS_STATUS='FREEZED',INVOICE_ID=@IID 
					WHERE  (PROVIDER_ID = @PROVIDER_ID  OR PROVIDER_ID in (SELECT provider_id from tblProvider where Provider_GroupName in  (select Provider_GroupName from tblProvider WHERE Provider_Id = @PROVIDER_ID)))
					AND (TRANSACTIONS_STATUS IS NULL or TRANSACTIONS_STATUS = 'CONFIRMED') AND TRANSACTIONS_TYPE IN ('RFB')
		
			

		UPDATE TBLTRANSACTIONS SET TRANSACTIONS_STATUS='FREEZED',INVOICE_ID=@IID WHERE PROVIDER_ID=@PROVIDER_ID AND (TRANSACTIONS_STATUS IS NULL or TRANSACTIONS_STATUS = 'CONFIRMED') AND TRANSACTIONS_TYPE IN ('CRED','EXPF','EXPP','EXPC') and DomainId=@DomainId    

END 
END

