create PROCEDURE [dbo].[LCJ_UpdateClientDetails] (
	@PROVIDER_BILLING FLOAT
	,@PROVIDER_INTBILLING FLOAT
	,@PROVIDER_INITIAL_BILLING FLOAT
	,@PROVIDER_INITIAL_INTBILLING FLOAT
	,@COST_BALANCE DECIMAL(19, 2)
	,@INVOICE_TYPE VARCHAR(5)
	,@PROVIDER_FF NCHAR(20)
	,@PROVIDER_RETURNFF NCHAR(20)
	,@PROVIDER_SEESFF VARCHAR(20)
	,@PROVIDER_SEESRFF VARCHAR(20)
	,@PROVIDER_INVOICEDFF VARCHAR(20)
	,@PROVIDER_ATTACHCHECKS VARCHAR(100)
	,@PROVIDER_ID INT
	)
AS
BEGIN
	UPDATE TBLPROVIDER
	SET Provider_Billing = @PROVIDER_BILLING
		,Provider_IntBilling = @PROVIDER_INTBILLING
		,Provider_Initial_Billing = @PROVIDER_INITIAL_BILLING
		,Provider_Initial_IntBilling = @PROVIDER_INITIAL_INTBILLING
		,COST_BALANCE = @COST_BALANCE
		,Invoice_Type = @INVOICE_TYPE
		,PROVIDER_FF = @PROVIDER_FF
		,PROVIDER_RETURNFF = @PROVIDER_RETURNFF
		,PROVIDER_SEESFF = @PROVIDER_SEESFF
		,PROVIDER_SEESRFF = @PROVIDER_SEESRFF
		,Provider_InvoicedFF = @PROVIDER_INVOICEDFF
		,Provider_attachChecks = @PROVIDER_ATTACHCHECKS
	WHERE PROVIDER_ID = @PROVIDER_ID
END
