CREATE PROCEDURE [dbo].[LCJ_INSERTINTODAILYSUMMONS] (
@MIDS NVARCHAR(3000)
)
as
begin
declare
@ST NVARCHAR(3500)

SET @MIDS = REPLACE(@MIDS,' ','')

TRUNCATE TABLE DAILYSUMMONS

SET @ST = 'SELECT DISTINCT CASE_ID FROM TBLCASE WHERE CASE_ID IN (''' + REPLACE(@MIDS,',',''',''')+ ''') order by case_id'

print @st

INSERT INTO DAILYSUMMONS
EXEC SP_EXECUTESQL @ST

	
end

