
CREATE PROCEDURE [dbo].[LCJ_GETCLIENTACCOUNTDETAILS] (
	@DomainId NVARCHAR(50)
	,@Accountid VARCHAR(50)
	)
AS
SELECT *
FROM TBLCLIENTACCOUNT(NOLOCK)
WHERE ACCOUNT_ID = @Accountid
	AND DomainId = @DomainId
