CREATE TABLE [dbo].[Auto_Packet_Info] (
    [DomainId]               VARCHAR (100)  NOT NULL,
    [Case_Id]                VARCHAR (100)  NOT NULL,
    [Case_AutoId]            VARCHAR (100)  NULL,
    [Case_Code]              VARCHAR (100)  NULL,
    [PacketID]               VARCHAR (200)  NULL,
    [InjuredParty_LastName]  VARCHAR (200)  NULL,
    [InjuredParty_FirstName] VARCHAR (200)  NULL,
    [InsuredParty_LastName]  VARCHAR (200)  NULL,
    [InsuredParty_FirstName] VARCHAR (200)  NULL,
    [Provider_Name]          VARCHAR (1000) NULL,
    [InsuranceCompany_Name]  VARCHAR (100)  NULL,
    [Claim_Amount]           MONEY          NULL,
    [Claim_Balance]          MONEY          NULL,
    [Paid_Amount]            MONEY          NULL,
    [Fee_Schedule]           MONEY          NULL,
    [FS_Balance]             MONEY          NULL,
    [Status]                 VARCHAR (500)  NULL,
    [Initial_Status]         VARCHAR (500)  NULL,
    [Accident_Date]          DATETIME       NULL,
    [Ins_Claim_Number]       VARCHAR (100)  NULL,
    [Policy_Number]          VARCHAR (100)  NULL,
    [Provider_GroupName]     VARCHAR (500)  NULL,
    [Status_Age]             INT            NULL,
    [DateOfService_Start]    DATETIME       NULL,
    [DateOfService_End]      DATETIME       NULL,
    [Date_BillSent]          DATETIME       NULL,
    [DenialReasons_Type]     VARCHAR (2000) NULL,
    [ServiceType]            VARCHAR (500)  NULL,
    [Provider_Id]            INT            NULL,
    [InsuranceCompany_Id]    INT            NULL,
    [Date_Opened]            DATETIME       NULL,
    [Date_Status_Changed]    DATETIME       NULL,
    [packet_type]            VARCHAR (100)  NULL,
    CONSTRAINT [PK_Auto_Packet_Info] PRIMARY KEY CLUSTERED ([DomainId] ASC, [Case_Id] ASC)
);

