CREATE TABLE [dbo].[DailyAdditional_Case_Details] (
    [Date_report_ran]                  DATETIME       NULL,
    [portfolio]                        NVARCHAR (50)  NULL,
    [case_id]                          NVARCHAR (100) NULL,
    [InsuredParty_FirstName]           NVARCHAR (100) NULL,
    [InsuredParty_LastName]            NVARCHAR (100) NULL,
    [InsuranceCompany_Name]            NVARCHAR (100) NULL,
    [CPT1]                             NVARCHAR (100) NULL,
    [CPT2]                             NVARCHAR (100) NULL,
    [CPT3]                             NVARCHAR (100) NULL,
    [CPT4]                             NVARCHAR (100) NULL,
    [MOD1]                             NVARCHAR (100) NULL,
    [MOD2]                             NVARCHAR (100) NULL,
    [MOD3]                             NVARCHAR (100) NULL,
    [MOD4]                             NVARCHAR (100) NULL,
    [DOS]                              NVARCHAR (100) NULL,
    [Project_Code]                     NVARCHAR (100) NULL,
    [Medical_Provider]                 NVARCHAR (100) NULL,
    [Specialty]                        NVARCHAR (100) NULL,
    [Bill_number]                      NVARCHAR (100) NULL,
    [Patient_no_Medic]                 NVARCHAR (100) NULL,
    [Accident_Date]                    DATETIME       NULL,
    [DOCTOR_NAME]                      NVARCHAR (100) NULL,
    [Units]                            NVARCHAR (100) NULL,
    [ICD10_1]                          NVARCHAR (100) NULL,
    [ICD10_2]                          NVARCHAR (100) NULL,
    [ICD10_3]                          NVARCHAR (100) NULL,
    [billing_date]                     DATETIME       NULL,
    [bill_type]                        NVARCHAR (100) NULL,
    [total_billed_amt]                 NVARCHAR (100) NULL,
    [Bill_Adjustment]                  NVARCHAR (100) NULL,
    [Purchase_Balance]                 NVARCHAR (100) NULL,
    [Purchase_Price]                   NVARCHAR (100) NULL,
    [Policy_Number]                    NVARCHAR (100) NULL,
    [Note]                             NVARCHAR (200) NULL,
    [First_Party_Case_Status]          NVARCHAR (100) NULL,
    [Case_Evaluation_Date]             DATETIME       NULL,
    [First_Party_Suit_Filed_Date]      NVARCHAR (100) NULL,
    [court_type]                       NVARCHAR (100) NULL,
    [court_county]                     NVARCHAR (100) NULL,
    [First_Party_Attorney]             NVARCHAR (100) NULL,
    [First_Party_LawFirm]              NVARCHAR (100) NULL,
    [Attorney_frmBiller_Note]          NVARCHAR (100) NULL,
    [Our_Attorney]                     NVARCHAR (100) NULL,
    [Our_Attorney_Law_Firm]            NVARCHAR (100) NULL,
    [Law_Suit_Type]                    NVARCHAR (100) NULL,
    [Purchase_Date]                    DATETIME       NULL,
    [Settledby_First_Party_Litigation] NVARCHAR (100) NULL,
    [Total_Litigation_Collection_1]    NVARCHAR (100) NULL,
    [Court_Fees_1]                     NVARCHAR (100) NULL,
    [Litigation_Fees_1]                NVARCHAR (100) NULL,
    [Net_Litigation_Collection_1]      NVARCHAR (100) NULL,
    [Payment_no_1]                     NVARCHAR (100) NULL,
    [Cheque_Date_1]                    DATETIME       NULL,
    [Denied_Insurance_Company]         NVARCHAR (100) NULL,
    [Percentage_Collected]             NVARCHAR (100) NULL,
    [Current_Balance_per_patient]      NVARCHAR (100) NULL,
    [Aging_months_past_dos]            NVARCHAR (50)  NULL,
    [domainid]                         NVARCHAR (100) NULL
);

