CREATE TABLE [dbo].[deletedInsuranceCompanies] (
    [InsuranceCompany_Id]               INT             IDENTITY (1, 1) NOT NULL,
    [InsuranceCompany_Name]             VARCHAR (250)   NULL,
    [InsuranceCompany_SuitName]         VARCHAR (250)   NULL,
    [InsuranceCompany_Type]             VARCHAR (40)    NULL,
    [InsuranceCompany_Local_Address]    VARCHAR (250)   NULL,
    [InsuranceCompany_Local_City]       VARCHAR (100)   NULL,
    [InsuranceCompany_Local_State]      VARCHAR (100)   NULL,
    [InsuranceCompany_Local_Zip]        VARCHAR (100)   NULL,
    [InsuranceCompany_Local_Phone]      VARCHAR (100)   NULL,
    [InsuranceCompany_Local_Fax]        VARCHAR (100)   NULL,
    [InsuranceCompany_Perm_Address]     VARCHAR (250)   NULL,
    [InsuranceCompany_Perm_City]        VARCHAR (100)   NULL,
    [InsuranceCompany_Perm_State]       VARCHAR (100)   NULL,
    [InsuranceCompany_Perm_Zip]         VARCHAR (100)   NULL,
    [InsuranceCompany_Perm_Phone]       VARCHAR (100)   NULL,
    [InsuranceCompany_Perm_Fax]         VARCHAR (100)   NULL,
    [InsuranceCompany_Contact]          VARCHAR (255)   NULL,
    [InsuranceCompany_Email]            VARCHAR (100)   NULL,
    [InsuranceCompany_GroupName]        VARCHAR (200)   NULL,
    [Active]                            INT             NULL,
    [SZ_SHORT_NAME]                     NVARCHAR (100)  NULL,
    [BILLING_ADDRESS]                   VARCHAR (100)   NULL,
    [BILLING_CITY]                      VARCHAR (50)    NULL,
    [BILLING_STATE]                     VARCHAR (2)     NULL,
    [BILLING_ZIP]                       VARCHAR (10)    NULL,
    [ActiveStatus]                      BIT             NULL,
    [InsuranceCompany_Initial_Address]  VARCHAR (250)   NULL,
    [InsuranceCompany_Initial_City]     VARCHAR (100)   NULL,
    [InsuranceCompany_Initial_State]    VARCHAR (100)   NULL,
    [InsuranceCompany_Initial_Zip]      VARCHAR (100)   NULL,
    [InsuranceCompany_Address2_Address] NVARCHAR (100)  NULL,
    [InsuranceCompany_Address2_City]    NVARCHAR (100)  NULL,
    [InsuranceCompany_Address2_State]   NVARCHAR (100)  NULL,
    [InsuranceCompany_Address2_Zip]     NVARCHAR (100)  NULL,
    [InsuranceCompany_Address2_Phone]   NVARCHAR (100)  NULL,
    [InsuranceCompany_Address2_Fax]     NVARCHAR (100)  NULL,
    [gbb_status]                        NVARCHAR (1000) NULL,
    [gbb_initial_status]                NVARCHAR (1000) NULL,
    [RCF_initial_status]                NVARCHAR (1000) NULL,
    [DomainId]                          NVARCHAR (50)   NOT NULL,
    [InsuranceCompanyGroup_ID]          INT             NULL
);

