CREATE TABLE [dbo].[H_TXN_DOCUMENT_UPLOAD] (
    [I_ID]             BIGINT         NOT NULL,
    [SZ_PROCESS_ID]    NVARCHAR (50)  NOT NULL,
    [SZ_USER_ID]       NVARCHAR (50)  NOT NULL,
    [SZ_FILENAME]      NVARCHAR (500) NOT NULL,
    [DT_UPLOAD_TIME]   DATETIME       NOT NULL,
    [SZ_CASE_ID]       NVARCHAR (50)  NOT NULL,
    [I_NOTES_ID]       INT            NOT NULL,
    [SZ_CAPTION]       NVARCHAR (255) NULL,
    [DT_DELETE_TIME]   DATETIME       CONSTRAINT [DF__H_TXN_DOC__DT_DE__302F0D3D] DEFAULT (getdate()) NULL,
    [DT_DEL_USER_NAME] NVARCHAR (50)  NULL,
    [DomainId]         NVARCHAR (512) DEFAULT ('h1') NOT NULL
);

