CREATE TABLE [dbo].[MasterNew] (
    [Provider]       VARCHAR (500) NULL,
    [Portfolio]      VARCHAR (50)  NULL,
    [Purchase Date]  VARCHAR (50)  NULL,
    [Insured]        VARCHAR (500) NULL,
    [Ins  Company]   VARCHAR (500) NULL,
    [Claim #]        VARCHAR (500) NULL,
    [DOL]            VARCHAR (50)  NULL,
    [DOS]            VARCHAR (50)  NULL,
    [DOFN]           VARCHAR (50)  NULL,
    [Invoice Amount] VARCHAR (50)  NULL,
    [Column 10]      VARCHAR (50)  NULL,
    [Case No ]       VARCHAR (500) NULL,
    [Filing Date]    VARCHAR (50)  NULL,
    [Attorney]       VARCHAR (500) NULL,
    [County Filed]   VARCHAR (500) NULL,
    [Settled Date]   VARCHAR (50)  NULL,
    [Paid Date]      VARCHAR (50)  NULL,
    [Paid Amount]    VARCHAR (50)  NULL,
    [Notes ]         VARCHAR (500) NULL,
    [Status]         VARCHAR (500) NULL,
    [FirstName]      VARCHAR (100) NULL,
    [LastName]       VARCHAR (100) NULL
);

