CREATE TABLE [dbo].[Mcc2020_1] (
    [Provider]            NVARCHAR (255) NULL,
    [PatientLastName]     NVARCHAR (255) NULL,
    [PatientFirstName]    NVARCHAR (255) NULL,
    [Initial_Status]      NVARCHAR (255) NULL,
    [Status]              NVARCHAR (255) NULL,
    [InsuranceName]       NVARCHAR (255) NULL,
    [DateofAccident]      NVARCHAR (255) NULL,
    [Claim Number]        NVARCHAR (255) NULL,
    [PolicyNumber]        NVARCHAR (255) NULL,
    [BILL_NUMBER]         NVARCHAR (255) NULL,
    [FltBillAmount]       FLOAT (53)     NULL,
    [Paid_Amount]         NVARCHAR (255) NULL,
    [Defendant_Name]      NVARCHAR (255) NULL,
    [Attorney_Name]       NVARCHAR (255) NULL,
    [IndexOrAAA_Number]   NVARCHAR (255) NULL,
    [DateOfService_Start] DATETIME       NULL,
    [DateOfService_End]   DATETIME       NULL,
    [Date_AAA_Arb_Filed]  NVARCHAR (255) NULL,
    [AtlasProviderId]     NVARCHAR (255) NULL,
    [AtlasInsuranceId]    NVARCHAR (255) NULL,
    [Transferd_Date]      NVARCHAR (255) NULL,
    [Transferd_Status]    NVARCHAR (255) NULL,
    [AUTOID]              FLOAT (53)     NULL,
    [case_code]           NVARCHAR (255) NULL,
    [Date_BillSent]       NVARCHAR (255) NULL,
    [Doctor_Name]         NVARCHAR (255) NULL,
    [SERVICE_TYPE]        NVARCHAR (255) NULL
);

