CREATE TABLE [dbo].[MCC_05192020] (
    [Provider]         NVARCHAR (255) NULL,
    [Patient ID]       NVARCHAR (255) NULL,
    [PatientLastName]  NVARCHAR (255) NULL,
    [PatientFirstName] NVARCHAR (255) NULL,
    [PatientDOB]       DATETIME       NULL,
    [CaseTypeName]     NVARCHAR (255) NULL,
    [InsuranceName]    NVARCHAR (255) NULL,
    [DateofAccident]   DATETIME       NULL,
    [Claim Number]     FLOAT (53)     NULL,
    [PolicyNumber]     NVARCHAR (255) NULL,
    [BillType]         NVARCHAR (255) NULL,
    [TreatingProvider] NVARCHAR (255) NULL,
    [FirstVisitDate]   DATETIME       NULL,
    [LastVisitDate]    DATETIME       NULL,
    [BillDate]         DATETIME       NULL,
    [FltBillAmount]    MONEY          NULL,
    [FltPaid]          MONEY          NULL,
    [FltBalance]       NVARCHAR (255) NULL,
    [InitialStatus]    NVARCHAR (255) NULL,
    [Notes]            NVARCHAR (255) NULL,
    [ID]               NVARCHAR (255) NULL,
    [DomainId]         NVARCHAR (255) NULL,
    [AtlasProviderId]  FLOAT (53)     NULL,
    [IsDuplicateCase]  NVARCHAR (255) NULL,
    [AtlasInsuranceId] NVARCHAR (255) NULL,
    [GBB_Type]         NVARCHAR (255) NULL,
    [Transferd_Date]   NVARCHAR (255) NULL,
    [Transferd_Status] NVARCHAR (255) NULL
);

