CREATE TABLE [dbo].[MedClaimMasterNew] (
    [FirstName]                  VARCHAR (50) NULL,
    [LastName]                   VARCHAR (50) NULL,
    [Insurance]                  VARCHAR (50) NULL,
    [PreCTransactionPayment]     VARCHAR (50) NULL,
    [PreCTransactionDate]        VARCHAR (50) NULL,
    [PreCTransactionPayment2]    VARCHAR (50) NULL,
    [PreCTransactionDate2]       VARCHAR (50) NULL,
    [Deductible1]                VARCHAR (50) NULL,
    [Deductible2]                VARCHAR (50) NULL,
    [Interest1]                  VARCHAR (50) NULL,
    [Interest2]                  VARCHAR (50) NULL,
    [AttorneyFee1]               VARCHAR (50) NULL,
    [AttorneyFee2]               VARCHAR (50) NULL,
    [TotalLitigationCollection1] VARCHAR (50) NULL,
    [CourtFees 1]                VARCHAR (50) NULL,
    [LitigationFees1]            VARCHAR (50) NULL,
    [NetLitigationCollection]    VARCHAR (50) NULL,
    [LitigationPaymentDate1]     VARCHAR (50) NULL,
    [TotalLitigationCollection2] VARCHAR (50) NULL,
    [CourtFees2]                 VARCHAR (50) NULL,
    [LitigationFees2]            VARCHAR (50) NULL,
    [NetLitigationCollection2]   VARCHAR (50) NULL,
    [LitigationPaymentDate2]     VARCHAR (50) NULL
);

