CREATE TABLE [dbo].[MST_DENIAL_CATEGORY] (
    [I_CATEGORY_ID]     INT            IDENTITY (1, 1) NOT NULL,
    [SZ_CATEGORY_NAME]  NVARCHAR (50)  NOT NULL,
    [SZ_CATEGORY_COLOR] NVARCHAR (50)  NULL,
    [DomainId]          NVARCHAR (512) DEFAULT ('h1') NOT NULL
);

