CREATE TABLE [dbo].[MST_PROCESS] (
    [SZ_PROCESS_CODE]                 NVARCHAR (10)  NOT NULL,
    [SZ_PROCESS_NAME]                 NVARCHAR (100) NOT NULL,
    [BT_DEPENDS_ON_INSURANCE_COMPANY] BIT            DEFAULT ((0)) NULL,
    [DomainId]                        NVARCHAR (512) DEFAULT ('h1') NOT NULL,
    CONSTRAINT [PK_SZ_PROCESS_CODE] PRIMARY KEY CLUSTERED ([SZ_PROCESS_CODE] ASC),
    UNIQUE NONCLUSTERED ([SZ_PROCESS_NAME] ASC)
);

