CREATE TABLE [dbo].[MST_TEMPLATES] (
    [I_TEMPLATE_ID]        INT            IDENTITY (1, 1) NOT NULL,
    [SZ_TEMPLATE_NAME]     NVARCHAR (500) NOT NULL,
    [SZ_TEMPLATE_FORMAT]   CHAR (5)       NOT NULL,
    [SZ_TEMPLATE_PATH]     NVARCHAR (500) NOT NULL,
    [SZ_TEMPLATE_FILENAME] NVARCHAR (500) NOT NULL,
    [fk_default_node_id]   INT            NULL,
    [DomainId]             NVARCHAR (100) DEFAULT ('h1') NOT NULL,
    CONSTRAINT [PK_MST_TEMPLATES] PRIMARY KEY CLUSTERED ([I_TEMPLATE_ID] ASC)
);

