CREATE TABLE [dbo].[tbl_client_other_details] (
    [DomainID]                 VARCHAR (50)   NOT NULL,
    [CLIENT_ATTORNEY_NAME_1]   VARCHAR (200)  NULL,
    [POSTAGE_ADDRESS]          VARCHAR (500)  NULL,
    [NOTARY_DETAILS]           VARCHAR (500)  NULL,
    [NOTARY_SIGNED_BY_NAME]    NVARCHAR (200) NULL,
    [CLIENT_ATTORNEY_NAME_2]   VARCHAR (200)  NULL,
    [CLIENT_ATTORNEY_NAME_3]   VARCHAR (200)  NULL,
    [CLIENT_ATTORNEY_NAME_4]   VARCHAR (200)  NULL,
    [CLIENT_ATTORNEY_NAME_5]   VARCHAR (200)  NULL,
    [ADMINISTRATIVE_ASSISTANT] NVARCHAR (200) NULL,
    CONSTRAINT [PK_tbl_client_other_details] PRIMARY KEY CLUSTERED ([DomainID] ASC)
);

