CREATE TABLE [dbo].[TBL_CHAR] (
    [CHAR_STRING] NVARCHAR (10)  NOT NULL,
    [CHAR_VALUE]  NVARCHAR (50)  NOT NULL,
    [CHAR_ASCII]  NCHAR (10)     NULL,
    [DomainId]    NVARCHAR (512) DEFAULT ('h1') NOT NULL
);

