CREATE TABLE [dbo].[tbl_CPT_Payment_Details] (
    [CPT_Pay_Id]                INT             IDENTITY (1, 1) NOT NULL,
    [CPT_ATUO_ID]               INT             NULL,
    [CPT_Code]                  DECIMAL (18)    NULL,
    [Description]               NVARCHAR (500)  NULL,
    [Case_ID]                   NVARCHAR (50)   NULL,
    [Prev_Collected_Amount]     DECIMAL (18, 2) NULL,
    [Current_Paid]              DECIMAL (18, 2) NULL,
    [Created_By]                NVARCHAR (500)  NULL,
    [Created_Date]              DATETIME        NULL,
    [Modified_By]               NVARCHAR (500)  NULL,
    [Modified_Date]             DATETIME        NULL,
    [Domainid]                  NVARCHAR (50)   NULL,
    [Transaction_Id]            INT             NULL,
    [Current_Interest]          DECIMAL (18, 2) NULL,
    [Prev_Deductible]           DECIMAL (18, 2) NULL,
    [Current_Deductible]        DECIMAL (18, 2) NULL,
    [Prev_Intrest]              DECIMAL (18, 2) NULL,
    [Prev_AttorneyFee]          DECIMAL (18, 2) NULL,
    [Current_AttorneyFee]       DECIMAL (18, 2) NULL,
    [Prev_LIT_Collected_Amount] DECIMAL (18, 2) NULL,
    [Current_LIT_Paid]          DECIMAL (18, 2) NULL,
    [Prev_LIT_Intrest]          DECIMAL (18, 2) NULL,
    [Current_LIT_Interest]      DECIMAL (18, 2) NULL,
    [Prev_LIT_Fees]             DECIMAL (18, 2) NULL,
    [Current_LIT_Fees]          DECIMAL (18, 2) NULL,
    [Prev_LIT_CourtFee]         DECIMAL (18, 2) NULL,
    [Current_LIT_CourtFee]      DECIMAL (18, 2) NULL,
    [VAL_PAY_Freeze_Date]       DATETIME        NULL,
    [LIT_PAY_Freeze_Date]       DATETIME        NULL,
    [VAL_Cleared_Date]          DATETIME        NULL,
    [LIT_Cleared_Date]          DATETIME        NULL
);

