CREATE TABLE [dbo].[tblBasePath] (
    [BasePathId]                     INT           IDENTITY (1, 1) NOT NULL,
    [PhysicalBasePath]               VARCHAR (400) NULL,
    [VirtualBasePath]                VARCHAR (200) NULL,
    [DomainName]                     VARCHAR (512) NULL,
    [LawFirmDocDownloadPath]         VARCHAR (512) NULL,
    [LawFirmDoclogicalPath]          VARCHAR (512) NULL,
    [PacketPath]                     VARCHAR (512) NULL,
    [PACKET_DOC_URL]                 VARCHAR (512) NULL,
    [ArchivedDocumentUploadLocation] VARCHAR (512) NULL,
    [MergePth]                       VARCHAR (512) NULL,
    [BlankMergePth]                  VARCHAR (512) NULL,
    [DocumentManagerURL]             VARCHAR (512) NULL,
    [PatientInfoSaveFilePath]        VARCHAR (512) NULL,
    [PatientInfoOpenFilePath]        VARCHAR (512) NULL,
    [EXCEL_SHEET]                    VARCHAR (512) NULL,
    [FETCHEXCEL_SHEET]               VARCHAR (512) NULL,
    [TemplateDocsPath]               VARCHAR (512) NULL,
    [BillDownload]                   VARCHAR (512) NULL,
    [APIOpenFilePath]                VARCHAR (512) NULL,
    [APISaveFilePath]                VARCHAR (512) NULL,
    [NotesSaveFilePath]              VARCHAR (512) NULL,
    [NotesOpenFilePath]              VARCHAR (512) NULL,
    [BillingDocumentManagerUrl]      VARCHAR (512) NULL,
    [BILLING_FETCHEXCEL_SHEET]       VARCHAR (512) NULL,
    [BasePathType]                   INT           NULL,
    [ConnectionString]               VARCHAR (512) NULL,
    [PhysicalBaseSubPath]            VARCHAR (400) NULL,
    [DeletePhysicalFile]             BIT           DEFAULT ((0)) NULL,
    CONSTRAINT [PK_tblBasePath] PRIMARY KEY CLUSTERED ([BasePathId] ASC) WITH (FILLFACTOR = 80)
);

