CREATE TABLE [dbo].[tblcase_SA_OLD] (
    [Case_AutoId]                           INT             NOT NULL,
    [Case_Id]                               NVARCHAR (50)   NOT NULL,
    [Case_Code]                             VARCHAR (100)   NULL,
    [Provider_Code]                         VARCHAR (100)   NULL,
    [InsuranceCompany_Code]                 VARCHAR (100)   NULL,
    [Provider_Id]                           INT             NULL,
    [InsuranceCompany_Id]                   INT             NULL,
    [InjuredParty_LastName]                 NVARCHAR (100)  NULL,
    [InjuredParty_FirstName]                NVARCHAR (100)  NULL,
    [InjuredParty_Address]                  NVARCHAR (255)  NULL,
    [InjuredParty_City]                     NVARCHAR (40)   NULL,
    [InjuredParty_State]                    NVARCHAR (40)   NULL,
    [InjuredParty_Zip]                      NVARCHAR (40)   NULL,
    [InjuredParty_Phone]                    VARCHAR (100)   NULL,
    [InjuredParty_Misc]                     VARCHAR (50)    NULL,
    [InsuredParty_LastName]                 NVARCHAR (100)  NULL,
    [InsuredParty_FirstName]                NVARCHAR (100)  NULL,
    [InsuredParty_Address]                  NVARCHAR (255)  NULL,
    [InsuredParty_City]                     NVARCHAR (40)   NULL,
    [InsuredParty_State]                    NVARCHAR (40)   NULL,
    [InsuredParty_Zip]                      NVARCHAR (40)   NULL,
    [InsuredParty_Misc]                     VARCHAR (50)    NULL,
    [Accident_Date]                         DATETIME        NULL,
    [Accident_Address]                      NVARCHAR (255)  NULL,
    [Accident_City]                         NVARCHAR (40)   NULL,
    [Accident_State]                        NVARCHAR (40)   NULL,
    [Accident_Zip]                          NVARCHAR (40)   NULL,
    [Policy_Number]                         VARCHAR (40)    NULL,
    [Ins_Claim_Number]                      NVARCHAR (50)   NULL,
    [IndexOrAAA_Number]                     VARCHAR (40)    NULL,
    [Status]                                NVARCHAR (50)   NULL,
    [Old_Status]                            NVARCHAR (50)   NULL,
    [Defendant_Id]                          NVARCHAR (50)   NULL,
    [Date_Opened]                           DATETIME        NULL,
    [Date_Opened_Full]                      DATETIME        NULL,
    [Last_Status]                           VARCHAR (50)    NULL,
    [Initial_Status]                        NVARCHAR (50)   NULL,
    [Memo]                                  NVARCHAR (255)  NULL,
    [InjuredParty_Type]                     NVARCHAR (20)   NULL,
    [InsuredParty_Type]                     NVARCHAR (20)   NULL,
    [Adjuster_Id]                           INT             NULL,
    [DenialReasons_Type]                    NVARCHAR (50)   NULL,
    [Court_Id]                              INT             NULL,
    [Attorney_FileNumber]                   NVARCHAR (100)  NULL,
    [Group_Data]                            INT             NULL,
    [Group_Id]                              INT             NULL,
    [Date_Status_Changed]                   DATETIME        NULL,
    [Date_Answer_Received]                  DATETIME        NULL,
    [Motion_Date]                           DATETIME        NULL,
    [Trial_Date]                            CHAR (50)       NULL,
    [Attorney_Id]                           VARCHAR (50)    NULL,
    [Date_Answer_Expected]                  DATETIME        NULL,
    [Reply_Date]                            DATETIME        NULL,
    [Calendar_Part]                         VARCHAR (50)    NULL,
    [Motion_Type]                           VARCHAR (100)   NULL,
    [Whose_Motion]                          VARCHAR (50)    NULL,
    [Defense_Opp_Due]                       DATETIME        NULL,
    [Date_Ext_Of_Time_2]                    DATETIME        NULL,
    [XMotion_Type]                          VARCHAR (50)    NULL,
    [Case_Billing]                          FLOAT (53)      NULL,
    [DateOfService_Start]                   DATETIME        NULL,
    [DateOfService_End]                     DATETIME        NULL,
    [Claim_Amount]                          VARCHAR (100)   NULL,
    [Paid_Amount]                           VARCHAR (100)   NULL,
    [Date_BillSent]                         VARCHAR (250)   NULL,
    [Caption]                               NVARCHAR (1000) NULL,
    [Group_ClaimAmt]                        NVARCHAR (200)  NULL,
    [Group_PaidAmt]                         NVARCHAR (200)  NULL,
    [Group_Balance]                         NVARCHAR (200)  NULL,
    [Group_InsClaimNo]                      NVARCHAR (200)  NULL,
    [Group_All]                             NVARCHAR (500)  NULL,
    [Date_Packeted]                         DATETIME        NULL,
    [Group_Accident]                        NVARCHAR (200)  NULL,
    [Group_PolicyNum]                       NVARCHAR (200)  NULL,
    [GROUP_CASE_SEQUENCE]                   INT             NULL,
    [Our_SJ_Motion_Activity]                NVARCHAR (100)  NULL,
    [Their_SJ_Motion_Activity]              NVARCHAR (100)  NULL,
    [Our_Discovery_Demands]                 NVARCHAR (100)  NULL,
    [Our_Discovery_Responses]               NVARCHAR (100)  NULL,
    [Date_Summons_Printed]                  DATETIME        NULL,
    [Plaintiff_Discovery_Due_Date]          DATETIME        NULL,
    [Defendant_Discovery_Due_Date]          DATETIME        NULL,
    [Date_Bill_Submitted]                   DATETIME        NULL,
    [Date_Index_Number_Purchased]           DATETIME        NULL,
    [Date_Afidavit_Filed]                   DATETIME        NULL,
    [Date_Ext_Of_Time]                      DATETIME        NULL,
    [Date_Summons_Sent_Court]               DATETIME        NULL,
    [Date_Ext_Of_Time_3]                    DATETIME        NULL,
    [Served_To]                             VARCHAR (100)   NULL,
    [Served_On_Date]                        DATETIME        NULL,
    [Served_On_Time]                        VARCHAR (50)    NULL,
    [Date_Closed]                           DATETIME        NULL,
    [Notary_id]                             INT             NULL,
    [stips_signed_and_returned]             BIT             NULL,
    [stips_signed_and_returned_2]           BIT             NULL,
    [stips_signed_and_returned_3]           BIT             NULL,
    [Date_Demands_Printed]                  DATETIME        NULL,
    [Date_Disc_Conf_Letter_Printed]         DATETIME        NULL,
    [Date_Reply_To_Disc_Conf_Letter_Recd]   DATETIME        NULL,
    [psid]                                  INT             NULL,
    [Motion_Status]                         VARCHAR (50)    NULL,
    [BX_Originated]                         BIT             NULL,
    [BX_TEMP_ID]                            VARCHAR (50)    NULL,
    [Date_AAA_Arb_Filed]                    DATETIME        NULL,
    [Date_AAA_Concilation_Over]             DATETIME        NULL,
    [Arbitrator_ID]                         INT             NULL,
    [AAA_Confirmed_Date]                    DATETIME        NULL,
    [userId]                                NVARCHAR (100)  NULL,
    [Doctor_id]                             INT             NULL,
    [batchcode]                             NVARCHAR (50)   NULL,
    [location_id]                           INT             NULL,
    [GBDocument_RelativePath]               VARCHAR (MAX)   NULL,
    [GBDocument_AbsolutePath]               VARCHAR (MAX)   NULL,
    [INJURED_LAST_BKP]                      VARCHAR (500)   NULL,
    [Bit_FromGB]                            INT             NULL,
    [Injured_Caption]                       VARCHAR (8000)  NULL,
    [Provider_Caption]                      VARCHAR (8000)  NULL,
    [AAA_Decisions]                         VARCHAR (800)   NULL,
    [GB_Dms_Link]                           VARCHAR (800)   NULL,
    [GB_CASE_ID]                            NVARCHAR (500)  NULL,
    [GB_COMPANY_ID]                         NVARCHAR (500)  NULL,
    [GB_CASE_NO]                            NVARCHAR (500)  NULL,
    [DateNotice_TrialFiled]                 DATETIME        NULL,
    [DateFile_Trial_DeNovo]                 DATETIME        NULL,
    [DateAAA_packagePrinting]               DATETIME        NULL,
    [DateAAA_ResponceRecieved]              DATETIME        NULL,
    [Fee_Schedule]                          NUMERIC (18, 2) NULL,
    [Representetive]                        NVARCHAR (500)  NULL,
    [Representative_Contact_Number]         NVARCHAR (500)  NULL,
    [Denial_Date]                           DATETIME        NULL,
    [INSURANCECOMPANY_INITIAL_ADDRESS]      NVARCHAR (2000) NULL,
    [DOSHI_CASE_ID]                         INT             NULL,
    [OPENED_BY]                             NVARCHAR (50)   NULL,
    [Assigned_Attorney]                     VARCHAR (100)   NULL,
    [Caseid_no]                             INT             NULL,
    [Date_Open_Verification_Response_Sent1] DATETIME        NULL,
    [Date_Open_Verification_Response_Sent2] DATETIME        NULL,
    [Date_of_AAA_Awards]                    DATETIME        NULL,
    [Date_NAM_ARB_Filed]                    DATETIME        NULL,
    [Date_NAM_Confirmed]                    DATETIME        NULL,
    [Date_NAM_Response_Received]            DATETIME        NULL,
    [Date_of_NAM_Awards]                    DATETIME        NULL,
    [Date_NAM_Package_Printed]              DATETIME        NULL,
    [fhkp_status]                           VARCHAR (1000)  NULL,
    [firm_split_percent]                    NUMERIC (18, 2) NULL,
    [old_Case_id]                           VARCHAR (100)   NULL,
    [DomainId]                              NVARCHAR (50)   NULL,
    [FK_Packet_ID]                          INT             NULL,
    [purchaseDate]                          DATETIME        NULL,
    [PortfolioId]                           INT             NULL,
    [AttorneyFirmId]                        INT             NULL,
    [CASE_EVALUATION_DATE]                  DATETIME        NULL,
    [FIRST_PARTY_SUIT_DATE]                 DATETIME        NULL,
    [LITIGATION_PAYMENT_DATE]               DATETIME        NULL,
    [gbb_type]                              VARCHAR (10)    NULL
);

