CREATE TABLE [dbo].[tblcase_rfa_import_temp] (
    [Case_AutoId]                                                 INT             NOT NULL,
    [Case_Id]                                                     NVARCHAR (50)   NOT NULL,
    [Case_Code]                                                   VARCHAR (100)   NULL,
    [Provider_Code]                                               VARCHAR (16)    NULL,
    [InsuranceCompany_Code]                                       VARCHAR (80)    NULL,
    [Provider_Id]                                                 INT             NULL,
    [InsuranceCompany_Id]                                         INT             NULL,
    [InjuredParty_LastName]                                       NVARCHAR (100)  NULL,
    [InjuredParty_FirstName]                                      NVARCHAR (100)  NULL,
    [InjuredParty_Address]                                        VARCHAR (200)   NULL,
    [InjuredParty_City]                                           VARCHAR (40)    NULL,
    [InjuredParty_State]                                          VARCHAR (40)    NULL,
    [InjuredParty_Zip]                                            VARCHAR (40)    NULL,
    [InjuredParty_Phone]                                          VARCHAR (40)    NULL,
    [InjuredParty_Misc]                                           VARCHAR (16)    NULL,
    [InsuredParty_LastName]                                       NVARCHAR (100)  NULL,
    [InsuredParty_FirstName]                                      NVARCHAR (100)  NULL,
    [InsuredParty_Address]                                        VARCHAR (200)   NULL,
    [InsuredParty_City]                                           VARCHAR (80)    NULL,
    [InsuredParty_State]                                          VARCHAR (40)    NULL,
    [InsuredParty_Zip]                                            VARCHAR (40)    NULL,
    [InsuredParty_Misc]                                           VARCHAR (16)    NULL,
    [Accident_Date]                                               DATETIME        NULL,
    [Accident_Address]                                            VARCHAR (200)   NULL,
    [Accident_City]                                               VARCHAR (16)    NULL,
    [Accident_State]                                              VARCHAR (40)    NULL,
    [Accident_Zip]                                                VARCHAR (16)    NULL,
    [Policy_Number]                                               VARCHAR (40)    NULL,
    [Ins_Claim_Number]                                            NVARCHAR (50)   NULL,
    [IndexOrAAA_Number]                                           VARCHAR (40)    NULL,
    [Status]                                                      VARCHAR (500)   NULL,
    [Old_Status]                                                  NVARCHAR (500)  NULL,
    [Defendant_Id]                                                INT             NULL,
    [Date_Opened]                                                 DATETIME        NULL,
    [Date_Opened_Full]                                            DATETIME        NULL,
    [Last_Status]                                                 VARCHAR (80)    NULL,
    [Initial_Status]                                              NVARCHAR (100)  NULL,
    [Memo]                                                        VARCHAR (520)   NULL,
    [InjuredParty_Type]                                           VARCHAR (40)    NULL,
    [InsuredParty_Type]                                           VARCHAR (40)    NULL,
    [Adjuster_Id]                                                 INT             NULL,
    [DenialReasons_Type]                                          VARCHAR (80)    NULL,
    [Court_Id]                                                    INT             NULL,
    [Attorney_FileNumber]                                         VARCHAR (80)    NULL,
    [Group_Data]                                                  INT             NULL,
    [Group_Id]                                                    INT             NULL,
    [Date_Status_Changed]                                         DATETIME        NULL,
    [Date_Answer_Received]                                        DATETIME        NULL,
    [Motion_Date]                                                 DATETIME        NULL,
    [Trial_Date]                                                  CHAR (50)       NULL,
    [Attorney_Id]                                                 VARCHAR (16)    NULL,
    [Date_Answer_Expected]                                        DATETIME        NULL,
    [Reply_Date]                                                  DATETIME        NULL,
    [Calendar_Part]                                               VARCHAR (40)    NULL,
    [Motion_Type]                                                 VARCHAR (80)    NULL,
    [Whose_Motion]                                                VARCHAR (16)    NULL,
    [Defense_Opp_Due]                                             DATETIME        NULL,
    [Date_Ext_Of_Time_2]                                          DATETIME        NULL,
    [XMotion_Type]                                                VARCHAR (40)    NULL,
    [Case_Billing]                                                FLOAT (53)      NULL,
    [DateOfService_Start2]                                        VARCHAR (40)    NULL,
    [DateOfService_End2]                                          VARCHAR (40)    NULL,
    [DateOfService_Start]                                         DATETIME        NULL,
    [DateOfService_End]                                           DATETIME        NULL,
    [Claim_Amount]                                                NUMERIC (18, 2) NULL,
    [Paid_Amount]                                                 NUMERIC (18, 2) NULL,
    [Date_BillSent]                                               VARCHAR (80)    NULL,
    [Caption]                                                     VARCHAR (80)    NULL,
    [Group_ClaimAmt]                                              VARCHAR (40)    NULL,
    [Group_PaidAmt]                                               VARCHAR (16)    NULL,
    [Group_Balance]                                               VARCHAR (40)    NULL,
    [Group_InsClaimNo]                                            VARCHAR (40)    NULL,
    [Group_All]                                                   VARCHAR (40)    NULL,
    [Date_Packeted]                                               DATETIME        NULL,
    [Group_Accident]                                              VARCHAR (40)    NULL,
    [Group_PolicyNum]                                             VARCHAR (40)    NULL,
    [GROUP_CASE_SEQUENCE]                                         INT             NULL,
    [Our_SJ_Motion_Activity]                                      VARCHAR (40)    NULL,
    [Their_SJ_Motion_Activity]                                    VARCHAR (40)    NULL,
    [Our_Discovery_Demands]                                       VARCHAR (80)    NULL,
    [Our_Discovery_Responses]                                     VARCHAR (80)    NULL,
    [Date_Summons_Printed]                                        DATETIME        NULL,
    [Plaintiff_Discovery_Due_Date]                                DATETIME        NULL,
    [Defendant_Discovery_Due_Date]                                DATETIME        NULL,
    [Date_Bill_Submitted]                                         DATETIME        NULL,
    [Date_Index_Number_Purchased]                                 DATETIME        NULL,
    [Date_Afidavit_Filed]                                         DATETIME        NULL,
    [Date_Ext_Of_Time]                                            DATETIME        NULL,
    [Date_Summons_Sent_Court]                                     DATETIME        NULL,
    [Date_Ext_Of_Time_3]                                          DATETIME        NULL,
    [Served_To]                                                   VARCHAR (16)    NULL,
    [Served_On_Date]                                              DATETIME        NULL,
    [Served_On_Time]                                              VARCHAR (40)    NULL,
    [Date_Closed]                                                 DATETIME        NULL,
    [Notary_id]                                                   INT             NULL,
    [stips_signed_and_returned]                                   BIT             NULL,
    [stips_signed_and_returned_2]                                 BIT             NULL,
    [stips_signed_and_returned_3]                                 BIT             NULL,
    [Date_Demands_Printed]                                        DATETIME        NULL,
    [Date_Disc_Conf_Letter_Printed]                               DATETIME        NULL,
    [Date_Reply_To_Disc_Conf_Letter_Recd]                         DATETIME        NULL,
    [psid]                                                        INT             NULL,
    [Motion_Status]                                               VARCHAR (40)    NULL,
    [BX_Originated]                                               BIT             NULL,
    [BX_TEMP_ID]                                                  VARCHAR (40)    NULL,
    [Date_AAA_Arb_Filed]                                          DATETIME        NULL,
    [Date_AAA_Concilation_Over]                                   DATETIME        NULL,
    [Arbitrator_ID]                                               INT             NULL,
    [AAA_Confirmed_Date]                                          DATETIME        NULL,
    [userId]                                                      VARCHAR (16)    NULL,
    [Doctor_id]                                                   INT             NULL,
    [batchcode]                                                   VARCHAR (40)    NULL,
    [location_id]                                                 INT             NULL,
    [GBDocument_RelativePath]                                     VARCHAR (40)    NULL,
    [GBDocument_AbsolutePath]                                     VARCHAR (40)    NULL,
    [INJURED_LAST_BKP]                                            VARCHAR (40)    NULL,
    [Bit_FromGB]                                                  INT             NULL,
    [Injured_Caption]                                             VARCHAR (80)    NULL,
    [Provider_Caption]                                            VARCHAR (80)    NULL,
    [AAA_Decisions]                                               VARCHAR (16)    NULL,
    [GB_Dms_Link]                                                 VARCHAR (16)    NULL,
    [GB_CASE_ID]                                                  VARCHAR (16)    NULL,
    [GB_COMPANY_ID]                                               VARCHAR (40)    NULL,
    [GB_CASE_NO]                                                  VARCHAR (16)    NULL,
    [DateNotice_TrialFiled]                                       DATETIME        NULL,
    [DateFile_Trial_DeNovo]                                       DATETIME        NULL,
    [DateAAA_packagePrinting]                                     DATETIME        NULL,
    [DateAAA_ResponseRecieved]                                    DATETIME        NULL,
    [Fee_Schedule]                                                NUMERIC (18, 2) NULL,
    [Representetive]                                              VARCHAR (80)    NULL,
    [Representative_Contact_Number]                               VARCHAR (200)   NULL,
    [Denial_Date]                                                 DATETIME        NULL,
    [INSURANCECOMPANY_INITIAL_ADDRESS]                            VARCHAR (200)   NULL,
    [DOSHI_CASE_ID]                                               INT             NULL,
    [Assigned_Attorney]                                           VARCHAR (40)    NULL,
    [Caseid_no]                                                   INT             NULL,
    [Date_Open_Verification_Response_Sent1]                       DATETIME        NULL,
    [Date_Open_Verification_Response_Sent2]                       DATETIME        NULL,
    [Date_of_AAA_Awards]                                          DATETIME        NULL,
    [Date_NAM_ARB_Filed]                                          DATETIME        NULL,
    [Date_NAM_Confirmed]                                          DATETIME        NULL,
    [Date_NAM_Response_Received]                                  DATETIME        NULL,
    [Date_of_NAM_Awards]                                          DATETIME        NULL,
    [Date_NAM_Package_Printed]                                    DATETIME        NULL,
    [OPENED_BY]                                                   NVARCHAR (40)   NOT NULL,
    [fhkp_status]                                                 VARCHAR (80)    NULL,
    [firm_split_percent]                                          NUMERIC (18, 2) NULL,
    [old_Case_id]                                                 VARCHAR (40)    NULL,
    [Date_Case_Submitted_Carrier]                                 DATETIME        NULL,
    [FILING_FEE]                                                  DECIMAL (38, 2) NULL,
    [FILING_FEE_TAX]                                              DECIMAL (38, 2) NULL,
    [Date_Funding]                                                DATETIME        NULL,
    [Date_AAA_Client_Sett_Offer_Made]                             DATETIME        NULL,
    [fk_prep_status_id]                                           INT             NULL,
    [InsuranceCompany_Id_2]                                       INT             NULL,
    [DateTrialWon_NoticeEntryFiled]                               DATE            NULL,
    [FK_CaseType_Id]                                              INT             NULL,
    [Date_Rebuttal_Draft_Sent_ToProvider]                         DATETIME        NULL,
    [Date_Rebuttal_Received_FromProvider]                         DATETIME        NULL,
    [Date_Rebuttal_Draft_Requested_From_Provider]                 DATETIME        NULL,
    [Date_Rebuttal_Draft_Requested_From_RFAToLS]                  DATETIME        NULL,
    [Date_Rebuttal_Draft_Requested_From_LSToLS]                   DATETIME        NULL,
    [Date_Rebuttal_Draft_Sent_To_RFA]                             DATETIME        NULL,
    [Date_Rebuttal_Draft_Sent_To_AttorneyForReview]               DATETIME        NULL,
    [Date_AAA_Demand_Letter_To_Carrier_Attorney]                  DATETIME        NULL,
    [Date_AAA_Complaint_Letter_To_DFS_Carrier_Sent]               DATETIME        NULL,
    [Date_Our_AAA_Master_Notice_Filed]                            DATETIME        NULL,
    [Date_AAA_Master_Confirmed]                                   DATETIME        NULL,
    [Date_Our_AAA_Master_Brief_DueBy]                             DATETIME        NULL,
    [Date_Their_AAA_Master_Brief_DueBy]                           DATETIME        NULL,
    [Date_AAA_Master_Award_DueBy]                                 DATETIME        NULL,
    [Date_Our_AAA_Master_Brief_Filed]                             DATETIME        NULL,
    [Date_Their_AAA_Master_Brief_Received]                        DATETIME        NULL,
    [Date_AAA_Master_Award]                                       DATETIME        NULL,
    [Date_AAA_Master_Award_Requested_for_Reviewed]                DATETIME        NULL,
    [AAA_Master_Arbitrator_Info]                                  VARCHAR (200)   NULL,
    [Date_AAA_Document_Request_Sent_to_AAA_Carrier]               DATETIME        NULL,
    [Date_AAA_Document_Demand_Sent_to_AAA_Carrier]                DATETIME        NULL,
    [Date_AAA_Document_Request_Objection_Received_Carrier]        DATETIME        NULL,
    [Date_AAA_Document_Demand_Objection_Received_Carrier]         DATETIME        NULL,
    [Date_AAA_Document_Request_Directive_Received_Arbitrator]     DATETIME        NULL,
    [Date_AAA_Document_Demand_Directive_Received_Arbitrator]      DATETIME        NULL,
    [Date_AAA_Document_Request_Response_Received_Carrier]         DATETIME        NULL,
    [Date_AAA_Document_Demand_Response_Received_Carrier]          DATETIME        NULL,
    [Minor_case]                                                  VARCHAR (16)    NULL,
    [Date_Trial_Award]                                            DATETIME        NULL,
    [Date_14_Notice_Sent_To_Carrier]                              DATETIME        NULL,
    [Date_AAA_Brief_Analysis_sent_RFA]                            DATETIME        NULL,
    [AAA_Brief_Analysis_Type_sent_RFA]                            VARCHAR (80)    NULL,
    [AAA_Brief_Analysis_done_by]                                  VARCHAR (40)    NULL,
    [CaseTaken_BriefReview]                                       BIT             NULL,
    [Balance_On_Policy]                                           DECIMAL (10, 2) NULL,
    [Date_ID_pulled_for_collection_effort_1]                      DATETIME        NULL,
    [Date_RFA_Reached_Out_Carrier_1]                              DATETIME        NULL,
    [Date_ID_pulled_for_collection_effort_2]                      DATETIME        NULL,
    [Date_RFA_Reached_Out_Carrier_2]                              DATETIME        NULL,
    [Date_ID_pulled_for_collection_effort_3]                      DATETIME        NULL,
    [Date_RFA_Reached_Out_Carrier_3]                              DATETIME        NULL,
    [Carrier_will_issue_payment_1]                                VARCHAR (16)    NULL,
    [Carrier_will_issue_payment_2]                                VARCHAR (16)    NULL,
    [Carrier_will_issue_payment_3]                                VARCHAR (40)    NULL,
    [Outstanding]                                                 MONEY           NULL,
    [Date_TrialAward_written_Decision]                            DATETIME        NULL,
    [Date_AAA_admin_closed_notic_Recvd]                           DATETIME        NULL,
    [Date_AAA_admin_closed_notic_Sent_Review]                     DATETIME        NULL,
    [Datejudgment_Notice_Entry_Transcript_Sent]                   DATETIME        NULL,
    [Date_Judgment_Filed]                                         DATETIME        NULL,
    [Date_Judgment_Docketed]                                      DATETIME        NULL,
    [Date_Judgment_Execution_Sent_Marshall]                       DATETIME        NULL,
    [Date_Judgment_Execution_Sent_Sheriff]                        DATETIME        NULL,
    [Date_Judgment_Satisfaction_Filed]                            DATETIME        NULL,
    [Date_Judgment_Entered]                                       DATETIME        NULL,
    [Date_Judgment_Rejected]                                      DATETIME        NULL,
    [DATE_BULK_COLLECTION_LETTER_SENT_TO_DFS]                     DATETIME        NULL,
    [CONTINUED_ACCRUAL_STATUTORY_INTEREST_PRESERVED]              VARCHAR (40)    NULL,
    [DATE_90_DAY_NOTICE_RECEIVED]                                 DATETIME        NULL,
    [GBB_TYPE]                                                    VARCHAR (16)    NULL,
    [Settlement_Type_Stip]                                        VARCHAR (80)    NULL,
    [Loss_Withdrawal_Reason]                                      VARCHAR (80)    NULL,
    [Date_14_Default_Notice_Stipulation_Based_Sent]               DATETIME        NULL,
    [DATE_OF_AAA_ABEYANCE]                                        DATETIME        NULL,
    [IsDuplicateCase]                                             INT             NULL,
    [GB_LawFirm_ID]                                               VARCHAR (40)    NULL,
    [CaseFinalStatus]                                             NVARCHAR (255)  NULL,
    [Rebuttal_Status]                                             VARCHAR (40)    NULL,
    [filing_batchcode]                                            VARCHAR (40)    NULL,
    [DateConciliationLetter_Settlement]                           DATETIME        NULL,
    [Date_AAA_Partial_Payment_SentTo_Carrier]                     DATETIME        NULL,
    [FK_Packet_ID]                                                INT             NULL,
    [Date_Judgement_Filed_Satisfaction_Sent_Carrier]              DATETIME        NULL,
    [Date_Judgement_Satisfaction_Issued]                          DATETIME        NULL,
    [Date_COLLECTION_EFFORT_PARTIAL_PAYMENT_RECEIVED]             DATETIME        NULL,
    [COLLECTION_EFFORT_PARTIAL_PAYMENT_RECEIVED_INTEREST_ACCURES] DATETIME        NULL,
    [Balance_On_Policy_Bit]                                       BIT             NOT NULL,
    [Provider_Self_Pay]                                           DECIMAL (10, 2) NULL
);

