CREATE TABLE [dbo].[tblInsuranceGroup_Type] (
    [PK_INSURANCE_TYPE_ID] INT           IDENTITY (0, 1) NOT NULL,
    [INSURANCE_TYPE_NAME]  VARCHAR (255) NOT NULL,
    [DOMAIN_ID]            VARCHAR (25)  NOT NULL,
    PRIMARY KEY CLUSTERED ([PK_INSURANCE_TYPE_ID] ASC)
);

