CREATE TABLE [dbo].[tblInsuranceCompany_rfa_import_temp] (
    [InsuranceCompany_Id]               INT             NOT NULL,
    [InsuranceCompany_Name]             VARCHAR (250)   NULL,
    [InsuranceCompany_SuitName]         VARCHAR (250)   NULL,
    [InsuranceCompany_Type]             VARCHAR (40)    NULL,
    [InsuranceCompany_Local_Address]    VARCHAR (250)   NULL,
    [InsuranceCompany_Local_City]       VARCHAR (100)   NULL,
    [InsuranceCompany_Local_State]      VARCHAR (100)   NULL,
    [InsuranceCompany_Local_Zip]        VARCHAR (100)   NULL,
    [InsuranceCompany_Local_Phone]      VARCHAR (100)   NULL,
    [InsuranceCompany_Local_Fax]        VARCHAR (100)   NULL,
    [InsuranceCompany_Perm_Address]     VARCHAR (250)   NULL,
    [InsuranceCompany_Perm_City]        VARCHAR (100)   NULL,
    [InsuranceCompany_Perm_State]       VARCHAR (100)   NULL,
    [InsuranceCompany_Perm_Zip]         VARCHAR (100)   NULL,
    [InsuranceCompany_Perm_Phone]       VARCHAR (100)   NULL,
    [InsuranceCompany_Perm_Fax]         VARCHAR (100)   NULL,
    [InsuranceCompany_Contact]          VARCHAR (255)   NULL,
    [InsuranceCompany_Email]            VARCHAR (100)   NULL,
    [InsuranceCompany_GroupName]        VARCHAR (200)   NULL,
    [Active]                            INT             NULL,
    [SZ_SHORT_NAME]                     NVARCHAR (100)  NULL,
    [BILLING_ADDRESS]                   VARCHAR (100)   NULL,
    [BILLING_CITY]                      VARCHAR (50)    NULL,
    [BILLING_STATE]                     VARCHAR (2)     NULL,
    [BILLING_ZIP]                       VARCHAR (10)    NULL,
    [ActiveStatus]                      BIT             NULL,
    [InsuranceCompany_Initial_Address]  VARCHAR (250)   NULL,
    [InsuranceCompany_Initial_City]     VARCHAR (100)   NULL,
    [InsuranceCompany_Initial_State]    VARCHAR (100)   NULL,
    [InsuranceCompany_Initial_Zip]      VARCHAR (100)   NULL,
    [InsuranceCompany_Address2_Address] VARCHAR (250)   NULL,
    [InsuranceCompany_Address2_City]    NVARCHAR (100)  NULL,
    [InsuranceCompany_Address2_State]   NVARCHAR (100)  NULL,
    [InsuranceCompany_Address2_Zip]     NVARCHAR (100)  NULL,
    [InsuranceCompany_Address2_Phone]   NVARCHAR (100)  NULL,
    [InsuranceCompany_Address2_Fax]     NVARCHAR (100)  NULL,
    [gbb_status]                        NVARCHAR (1000) NULL,
    [gbb_initial_status]                NVARCHAR (1000) NULL,
    [RCF_initial_status]                NVARCHAR (1000) NULL,
    [FK_INSURANCE_GROUP_ID]             INT             NULL,
    [Date_InsuranceProfile_Created]     DATE            NULL,
    [Formerly_Known_As]                 NVARCHAR (MAX)  NULL,
    [Now_Known_As]                      NVARCHAR (MAX)  NULL,
    [Notes]                             NVARCHAR (MAX)  NULL,
    [FK_INSURANCE_TYPE_ID]              INT             NULL,
    [Date_insuranceProfile_Modified]    DATE            NULL,
    [Created_By]                        VARCHAR (200)   NULL,
    [fk_TPA_Group_ID]                   INT             NULL,
    [Modified_BY]                       VARCHAR (200)   NULL,
    [Formerly_Known_1]                  INT             NULL,
    [Formerly_Known_2]                  INT             NULL,
    [Formerly_Known_3]                  INT             NULL,
    [Formerly_Known_4]                  INT             NULL,
    [Formerly_Known_5]                  INT             NULL,
    [Formerly_Known_6]                  INT             NULL,
    [Now_KnownAs_1]                     INT             NULL,
    [Ins_Out_Of_State]                  INT             NULL,
    [Ins_GroupBasedOn]                  VARCHAR (MAX)   NULL,
    [Ins_GroupBasedOn_ID]               VARCHAR (MAX)   NULL
);

