CREATE TABLE [dbo].[tblProvider-JUNE12006] (
    [Provider_Id]            INT             NOT NULL,
    [Provider_Code]          NVARCHAR (100)  NULL,
    [Provider_Name]          NVARCHAR (100)  NULL,
    [Provider_Type]          VARCHAR (40)    NULL,
    [Provider_Local_Address] VARCHAR (255)   NULL,
    [Provider_Local_City]    VARCHAR (100)   NULL,
    [Provider_Local_State]   VARCHAR (100)   NULL,
    [Provider_Local_Zip]     VARCHAR (50)    NULL,
    [Provider_Local_Phone]   VARCHAR (100)   NULL,
    [Provider_Local_Fax]     VARCHAR (100)   NULL,
    [Provider_Contact]       VARCHAR (100)   NULL,
    [Provider_Perm_Address]  VARCHAR (255)   NULL,
    [Provider_Perm_City]     VARCHAR (100)   NULL,
    [Provider_Perm_State]    VARCHAR (100)   NULL,
    [Provider_Perm_Zip]      VARCHAR (50)    NULL,
    [Provider_Perm_Phone]    VARCHAR (100)   NULL,
    [Provider_Perm_Fax]      VARCHAR (100)   NULL,
    [Provider_Email]         VARCHAR (100)   NULL,
    [Provider_Billing]       FLOAT (53)      NULL,
    [Provider_Contact2]      VARCHAR (100)   NULL,
    [Provider_IntBilling]    VARCHAR (10)    NULL,
    [Invoice_Type]           VARCHAR (10)    NULL,
    [cost_balance]           MONEY           NULL,
    [Provider_Notes]         NVARCHAR (1000) NULL,
    [Provider_ReferredBy]    NVARCHAR (100)  NULL,
    [DomainId]               NVARCHAR (512)  DEFAULT ('h1') NOT NULL
);

