CREATE TABLE [dbo].[tblSettlements_rfa_import_temp] (
    [Settlement_Id]           INT             NOT NULL,
    [Settlement_Amount]       MONEY           NULL,
    [Settlement_Int]          MONEY           NULL,
    [Settlement_Af]           MONEY           NULL,
    [Settlement_Ff]           MONEY           NULL,
    [Settlement_Total]        MONEY           NULL,
    [Settlement_Date]         DATETIME        NULL,
    [Treatment_Id]            INT             NULL,
    [Case_Id]                 NVARCHAR (50)   NOT NULL,
    [User_Id]                 VARCHAR (50)    NOT NULL,
    [SettledWith]             NVARCHAR (2000) NULL,
    [Settlement_Notes]        NVARCHAR (2000) NULL,
    [Settlement_Rfund_PR]     MONEY           NULL,
    [Settlement_Rfund_Int]    MONEY           NULL,
    [Settlement_Rfund_Total]  MONEY           NULL,
    [Settlement_Rfund_date]   DATETIME        NULL,
    [Settlement_Rfund_Batch]  INT             NULL,
    [Settlement_Rfund_UserId] VARCHAR (50)    NULL,
    [Settlement_Batch]        VARCHAR (20)    NULL,
    [Settlement_SubBatch]     INT             NULL,
    [Settled_With_Name]       NVARCHAR (400)  NULL,
    [Settled_With_Phone]      NVARCHAR (100)  NULL,
    [Settled_With_Fax]        NVARCHAR (100)  NULL,
    [Settled_Type]            INT             NULL,
    [Settled_by]              INT             NULL,
    [Settled_Percent]         DECIMAL (5, 2)  NULL,
    [AdjusterID]              INT             NULL,
    [DefendantID]             INT             NULL,
    [AttorneyID]              INT             NULL,
    [Intrest_StartDate]       DATETIME        NULL,
    [Intrest_EndDate]         DATETIME        NULL,
    [Intrest_Percentage]      NUMERIC (18, 2) NULL,
    [Balance_Claim]           MONEY           NULL,
    [Balance_FeeSchedule]     MONEY           NULL,
    [Modified_By]             VARCHAR (50)    NULL,
    [Modified_Date]           DATE            NULL,
    [sett_late_int]           MONEY           NULL,
    [sett_late_af]            MONEY           NULL,
    [sett_master_af]          MONEY           NULL,
    [Balance_OnPolicy]        DECIMAL (10, 2) NULL,
    [sett_master_ff]          MONEY           NULL
);

