CREATE TABLE [dbo].[tblTreatment_rfa_import_temp] (
    [Treatment_Id]        INT             NOT NULL,
    [Case_Id]             NVARCHAR (50)   NULL,
    [DateOfService_Start] DATETIME        NULL,
    [DateOfService_End]   DATETIME        NULL,
    [Claim_Amount]        NUMERIC (19, 2) NULL,
    [Paid_Amount]         NUMERIC (19, 2) NULL,
    [Date_BillSent]       NVARCHAR (100)  NULL,
    [SERVICE_TYPE]        NVARCHAR (100)  NULL,
    [Settlement_Pctg]     FLOAT (53)      NULL,
    [Interest_Pctg]       FLOAT (53)      NULL,
    [AttorneyFee]         FLOAT (53)      NULL,
    [FilingFeeAmt]        FLOAT (53)      NULL,
    [SettlementInt]       FLOAT (53)      NULL,
    [CPT_Id]              INT             NULL,
    [BX_BILL_ID]          INT             NULL,
    [Date_Created]        DATETIME        NULL,
    [Litigation_Status]   INT             NULL,
    [account_number]      VARCHAR (20)    NULL,
    [BILL_NUMBER]         VARCHAR (100)   NULL,
    [Action_Type]         VARCHAR (100)   NULL,
    [Fee_Schedule]        NUMERIC (18, 2) NULL,
    [DENIALREASONS_TYPE1] VARCHAR (100)   NULL,
    [DenialReason_ID]     INT             NULL,
    [PeerReviewDoctor_ID] INT             NULL,
    [TreatingDoctor_ID]   INT             NULL,
    [DocumentStatus]      VARCHAR (100)   NULL,
    [Doctor_Id]           INT             NULL,
    [DENIALREASONS_TYPE]  VARCHAR (255)   NULL,
    [RefferingDoctor_ID]  INT             NULL
);

