CREATE TABLE [dbo].[tblTransactions_Details] (
    [TransactionsDetails_Id]     INT            IDENTITY (1, 1) NOT NULL,
    [Case_Id]                    NVARCHAR (100) NOT NULL,
    [DomainId]                   NVARCHAR (512) NOT NULL,
    [TT_PreC_1]                  MONEY          NULL,
    [TT_PreC_2]                  MONEY          NULL,
    [TT_PreC_3]                  MONEY          NULL,
    [TD_PreC_1]                  DATETIME       NULL,
    [TD_PreC_2]                  DATETIME       NULL,
    [TD_PreC_3]                  DATETIME       NULL,
    [TC_PreC_1]                  DATETIME       NULL,
    [TC_PreC_2]                  DATETIME       NULL,
    [TC_PreC_3]                  DATETIME       NULL,
    [TCN_PreC_1]                 NVARCHAR (50)  NULL,
    [TCN_PreC_2]                 NVARCHAR (50)  NULL,
    [TCN_PreC_3]                 NVARCHAR (50)  NULL,
    [TT_C_1]                     MONEY          NULL,
    [TT_C_2]                     MONEY          NULL,
    [TT_C_3]                     MONEY          NULL,
    [TD_C_1]                     DATETIME       NULL,
    [TD_C_2]                     DATETIME       NULL,
    [TD_C_3]                     DATETIME       NULL,
    [TC_C_1]                     DATETIME       NULL,
    [TC_C_2]                     DATETIME       NULL,
    [TC_C_3]                     DATETIME       NULL,
    [TCN_C_1]                    NVARCHAR (50)  NULL,
    [TCN_C_2]                    NVARCHAR (50)  NULL,
    [TCN_C_3]                    NVARCHAR (50)  NULL,
    [TT_AF_1]                    MONEY          NULL,
    [TT_AF_2]                    MONEY          NULL,
    [TT_AF_3]                    MONEY          NULL,
    [TD_AF_1]                    DATETIME       NULL,
    [TD_AF_2]                    DATETIME       NULL,
    [TD_AF_3]                    DATETIME       NULL,
    [TC_AF_1]                    DATETIME       NULL,
    [TC_AF_2]                    DATETIME       NULL,
    [TC_AF_3]                    DATETIME       NULL,
    [TCN_AF_1]                   NVARCHAR (50)  NULL,
    [TCN_AF_2]                   NVARCHAR (50)  NULL,
    [TCN_AF_3]                   NVARCHAR (50)  NULL,
    [TT_FF_1]                    MONEY          NULL,
    [TT_FF_2]                    MONEY          NULL,
    [TT_FF_3]                    MONEY          NULL,
    [TD_FF_1]                    DATETIME       NULL,
    [TD_FF_2]                    DATETIME       NULL,
    [TD_FF_3]                    DATETIME       NULL,
    [TC_FF_1]                    DATETIME       NULL,
    [TC_FF_2]                    DATETIME       NULL,
    [TC_FF_3]                    DATETIME       NULL,
    [TCN_FF_1]                   NVARCHAR (50)  NULL,
    [TCN_FF_2]                   NVARCHAR (50)  NULL,
    [TCN_FF_3]                   NVARCHAR (50)  NULL,
    [Transactions_Description_1] NVARCHAR (255) NULL
);

