CREATE TABLE [dbo].[TXN LATES_ACCESS] (
    [ACCESS_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [TEMPLATE_ID] INT           NOT NULL,
    [USER_TYPE]   VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TXN LATES_ACCESS] PRIMARY KEY CLUSTERED ([ACCESS_ID] ASC)
);

