CREATE TABLE [dbo].[TXN_DOCUMENT_UPLOAD] (
    [I_ID]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [SZ_PROCESS_ID]  NVARCHAR (50)  NOT NULL,
    [SZ_USER_ID]     NVARCHAR (50)  NOT NULL,
    [SZ_FILENAME]    NVARCHAR (500) NOT NULL,
    [DT_UPLOAD_TIME] DATETIME       NOT NULL,
    [SZ_CASE_ID]     NVARCHAR (50)  NOT NULL,
    [I_NOTES_ID]     INT            NULL,
    [SZ_CAPTION]     NVARCHAR (255) NULL,
    [DomainId]       NVARCHAR (512) DEFAULT ('h1') NOT NULL
);

