CREATE TABLE [dbo].[TXN_LIST_EMAIL_FILES] (
    [AUTO_ID]     INT            IDENTITY (1, 1) NOT NULL,
    [SZ_IMAGEID]  VARCHAR (500)  NULL,
    [SZ_FILENAME] VARCHAR (500)  NULL,
    [SZ_FILEPATH] VARCHAR (500)  NULL,
    [DomainId]    NVARCHAR (512) DEFAULT ('h1') NOT NULL
);

