CREATE TABLE [dbo].[TXN_TEMPLATES_ACCESS] (
    [ACCESS_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [TEMPLATE_ID] INT           NOT NULL,
    [USER_TYPE]   VARCHAR (100) NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_TXN LATES_ACCESS1] PRIMARY KEY CLUSTERED ([ACCESS_ID] ASC)
);

