CREATE TABLE [dbo].[XN_AMT_NorthShore1] (
    [Patient First Name]                                            NVARCHAR (255) NULL,
    [Patient Last Name]                                             NVARCHAR (255) NULL,
    [Prim Insurance]                                                NVARCHAR (255) NULL,
    [CPT]                                                           NVARCHAR (255) NULL,
    [MOD]                                                           FLOAT (53)     NULL,
    [DOS]                                                           DATETIME       NULL,
    [Project Code]                                                  NVARCHAR (255) NULL,
    [Medical Provider]                                              NVARCHAR (255) NULL,
    [Specialty]                                                     NVARCHAR (255) NULL,
    [Bill number]                                                   NVARCHAR (255) NULL,
    [Patient number Medic]                                          NVARCHAR (255) NULL,
    [Accident Date]                                                 NVARCHAR (255) NULL,
    [Referring Doctor]                                              NVARCHAR (255) NULL,
    [Rendering Physician]                                           NVARCHAR (255) NULL,
    [Units]                                                         NVARCHAR (255) NULL,
    [ICD10 1]                                                       NVARCHAR (255) NULL,
    [ICD10 2]                                                       NVARCHAR (255) NULL,
    [ICD10 3]                                                       NVARCHAR (255) NULL,
    [Billing Date]                                                  NVARCHAR (255) NULL,
    [Type of Bill]                                                  NVARCHAR (255) NULL,
    [Total Billed Amount]                                           FLOAT (53)     NULL,
    [Bill Adjustment]                                               NVARCHAR (255) NULL,
    [Voluntary payments 1]                                          NVARCHAR (255) NULL,
    [Voluntary payments 1 Date]                                     NVARCHAR (255) NULL,
    [Voluntary payments 2]                                          NVARCHAR (255) NULL,
    [Voluntary payments 2 Date]                                     NVARCHAR (255) NULL,
    [Voluntary payments 3]                                          NVARCHAR (255) NULL,
    [Voluntary payments 3 Date]                                     NVARCHAR (255) NULL,
    [Deductible]                                                    NVARCHAR (255) NULL,
    [Interest]                                                      NVARCHAR (255) NULL,
    [Purchase Balance]                                              FLOAT (53)     NULL,
    [Purchase Price]                                                FLOAT (53)     NULL,
    [Prim Policy ]                                                  NVARCHAR (255) NULL,
    [Note]                                                          NVARCHAR (255) NULL,
    [First Party Case Status]                                       NVARCHAR (255) NULL,
    [Case Evaluation Date]                                          NVARCHAR (255) NULL,
    [First Party Suit Filed Date]                                   NVARCHAR (255) NULL,
    [Court Type]                                                    NVARCHAR (255) NULL,
    [Court County]                                                  NVARCHAR (255) NULL,
    [First Party Attorney]                                          NVARCHAR (255) NULL,
    [First Party Law Firm]                                          NVARCHAR (255) NULL,
    [Attorney from Biller's Note]                                   NVARCHAR (255) NULL,
    [Our Attorney]                                                  NVARCHAR (255) NULL,
    [Our Attorney Law Firm]                                         NVARCHAR (255) NULL,
    [Law Suit Type]                                                 NVARCHAR (255) NULL,
    [Date of Purchase]                                              DATETIME       NULL,
    [Accounting Date]                                               DATETIME       NULL,
    [<<Purchase Debt]                                               NVARCHAR (255) NULL,
    [Voluntary Payment1]                                            NVARCHAR (255) NULL,
    [Deductible1]                                                   NVARCHAR (255) NULL,
    [Interest1]                                                     NVARCHAR (255) NULL,
    [Vol Attorney Fee1]                                             NVARCHAR (255) NULL,
    [Net Vol Pmt1]                                                  NVARCHAR (255) NULL,
    [Voluntary Payment Date1]                                       NVARCHAR (255) NULL,
    [Payment no#1]                                                  NVARCHAR (255) NULL,
    [Cheque Date1]                                                  NVARCHAR (255) NULL,
    [Cheque deposited in Collection Bank1]                          NVARCHAR (255) NULL,
    [Accounting Date1]                                              NVARCHAR (255) NULL,
    [Voluntary Payment2]                                            NVARCHAR (255) NULL,
    [Deductible2]                                                   NVARCHAR (255) NULL,
    [Interest2]                                                     NVARCHAR (255) NULL,
    [Vol Attorney Fee2]                                             NVARCHAR (255) NULL,
    [Net Vol Pmt2]                                                  NVARCHAR (255) NULL,
    [Voluntary Payment Date2]                                       NVARCHAR (255) NULL,
    [Payment no#2]                                                  NVARCHAR (255) NULL,
    [Cheque Date2]                                                  NVARCHAR (255) NULL,
    [Cheque deposited in Collection Bank2]                          NVARCHAR (255) NULL,
    [Accounting Date2]                                              NVARCHAR (255) NULL,
    [Settled by the First Party Litigation]                         NVARCHAR (255) NULL,
    [<<Voluntary Payments]                                          NVARCHAR (255) NULL,
    [Total Litigation Collection 1]                                 NVARCHAR (255) NULL,
    [Court Fees 1]                                                  NVARCHAR (255) NULL,
    [Litigation Fees 1]                                             NVARCHAR (255) NULL,
    [Net Litigation Collection 1]                                   NVARCHAR (255) NULL,
    [Litigation Payment Date 1]                                     NVARCHAR (255) NULL,
    [Payment no# 1]                                                 NVARCHAR (255) NULL,
    [Cheque Date 1]                                                 NVARCHAR (255) NULL,
    [Cheque deposited in Collection Bank? 1]                        NVARCHAR (255) NULL,
    [Accounting Date 1]                                             NVARCHAR (255) NULL,
    [Total Litigation Collection 2]                                 NVARCHAR (255) NULL,
    [Court Fees 2]                                                  NVARCHAR (255) NULL,
    [Litigation Fees 2]                                             NVARCHAR (255) NULL,
    [Net Litigation Collection 2]                                   NVARCHAR (255) NULL,
    [Litigation Payment Date 2]                                     NVARCHAR (255) NULL,
    [Payment no# 2]                                                 NVARCHAR (255) NULL,
    [Cheque Date 2]                                                 NVARCHAR (255) NULL,
    [Cheque deposited in Collection Bank? 2]                        NVARCHAR (255) NULL,
    [Accounting Date 2]                                             NVARCHAR (255) NULL,
    [<<Litigation Payments]                                         NVARCHAR (255) NULL,
    [Total Amount Billed]                                           NVARCHAR (255) NULL,
    [Total Vol Payments]                                            NVARCHAR (255) NULL,
    [Current Balance]                                               NVARCHAR (255) NULL,
    [First Party Case Status1]                                      NVARCHAR (255) NULL,
    [Case Evaluation Date1]                                         NVARCHAR (255) NULL,
    [First Party Suit Filed Date1]                                  NVARCHAR (255) NULL,
    [Court County1]                                                 NVARCHAR (255) NULL,
    [First Party Attorney1]                                         NVARCHAR (255) NULL,
    [First Party Law Firm1]                                         NVARCHAR (255) NULL,
    [Attorney from Biller's Note1]                                  NVARCHAR (255) NULL,
    [Our Attorney1]                                                 NVARCHAR (255) NULL,
    [Our Attorney Law Firm1]                                        NVARCHAR (255) NULL,
    [Law Suit Type1]                                                NVARCHAR (255) NULL,
    [Litigation Court]                                              NVARCHAR (255) NULL,
    [County/District]                                               NVARCHAR (255) NULL,
    [Our File Date / Motion Pending Date]                           NVARCHAR (255) NULL,
    [Case eval offer amount($)]                                     NVARCHAR (255) NULL,
    [Settlement Conference offer Amont]                             NVARCHAR (255) NULL,
    [Faciliation Offer Amount]                                      NVARCHAR (255) NULL,
    [Trial Decision Amount]                                         NVARCHAR (255) NULL,
    [Judges Name]                                                   NVARCHAR (255) NULL,
    [Recomendation]                                                 NVARCHAR (255) NULL,
    [Attorney Comment]                                              NVARCHAR (255) NULL,
    [Latest Offer]                                                  NVARCHAR (255) NULL,
    [% of Face]                                                     NVARCHAR (255) NULL,
    [Automatically Generated Decision]                              NVARCHAR (255) NULL,
    [Consistency]                                                   NVARCHAR (255) NULL,
    [Decided Action]                                                NVARCHAR (255) NULL,
    [Explanation]                                                   NVARCHAR (255) NULL,
    [Case Number]                                                   NVARCHAR (255) NULL,
    [Case Status_(for Assigned and First Party Claims)]             NVARCHAR (255) NULL,
    [<<Litigation Update]                                           NVARCHAR (255) NULL,
    [Denied by Insurance Company]                                   NVARCHAR (255) NULL,
    [% Collected]                                                   NVARCHAR (255) NULL,
    [Current Balance per Patient]                                   NVARCHAR (255) NULL,
    [Aging (months past DOS) as of 30 Jun 18]                       NVARCHAR (255) NULL,
    [Case closed bc cannot filing for liti]                         NVARCHAR (255) NULL,
    [Litigation Coding]                                             NVARCHAR (255) NULL,
    [Assignment date]                                               NVARCHAR (255) NULL,
    [Aging (months past assignment date) as of 30 Jun 18]           NVARCHAR (255) NULL,
    [<<Litigation Monitoring]                                       NVARCHAR (255) NULL,
    [Patient bill in Q1 Purchase Report?]                           NVARCHAR (255) NULL,
    [Patient bill in Exchange List (IN)?]                           NVARCHAR (255) NULL,
    [Patient bill in Exchange List (OUT)?]                          NVARCHAR (255) NULL,
    [Status_(Active or Exchanged)]                                  NVARCHAR (255) NULL,
    [<<Exchange History]                                            NVARCHAR (255) NULL,
    [CHECK FOR DUPLICATES:_CONCATENATE (LN+FN+PrimINs+CPT+MOD+DOS)] NVARCHAR (255) NULL
);

