CREATE TABLE [dbo].[XN_POMDetails] (
    [ACCOUNT]      NVARCHAR (255) NULL,
    [BILL NUMBER]  NVARCHAR (255) NULL,
    [POM ID]       NVARCHAR (255) NULL,
    [POM DATE]     NVARCHAR (255) NULL,
    [STAMPED DATE] NVARCHAR (255) NULL
);

