CREATE TABLE [dbo].[XN_TEMP_TABLE_DATA_MCCOLLUM] (
    [autoid]                 INT             IDENTITY (1, 1) NOT NULL,
    [SZ_CASE_ID]             INT             NULL,
    [SZ_CASE_NO]             INT             NULL,
    [SZ_PATIENT_FIRST_NAME]  NVARCHAR (1000) NULL,
    [SZ_PATIENT_LAST_NAME]   NVARCHAR (1000) NULL,
    [SZ_INSURANCE_NAME]      NVARCHAR (1000) NULL,
    [SZ_INSURANCE_ADDRESS]   NVARCHAR (1000) NULL,
    [SZ_INSURANCE_CITY]      NVARCHAR (255)  NULL,
    [SZ_STATE]               NVARCHAR (255)  NULL,
    [SZ_INSURANCE_ZIP]       NVARCHAR (100)  NULL,
    [SZ_INSURANCE_PHONE]     NVARCHAR (1000) NULL,
    [SZ_INSURANCE_EMAIL]     NVARCHAR (1000) NULL,
    [SZ_PATIENT_ADDRESS]     NVARCHAR (1000) NULL,
    [SZ_PATIENT_STREET]      NVARCHAR (1000) NULL,
    [SZ_PATIENT_CITY]        NVARCHAR (1000) NULL,
    [SZ_PATIENT_STATE]       NVARCHAR (1000) NULL,
    [SZ_PATIENT_ZIP]         NVARCHAR (1000) NULL,
    [SZ_PATIENT_PHONE]       NVARCHAR (1000) NULL,
    [SZ_POLICY_NUMBER]       NVARCHAR (1000) NULL,
    [SZ_CLAIM_NUMBER]        NVARCHAR (1000) NULL,
    [SZ_BILL_STATUS_NAME]    NVARCHAR (1000) NULL,
    [SZ_ATTORNEY_NAME]       NVARCHAR (1000) NULL,
    [SZ_ATTORNEY_LAST_NAME]  NVARCHAR (1000) NULL,
    [SZ_ATTORNEY_ADDRESS]    NVARCHAR (1000) NULL,
    [SZ_ATTORNEY_CITY]       NVARCHAR (1000) NULL,
    [SZ_ATTORNEY_STATE]      NVARCHAR (1000) NULL,
    [SZ_ATTORNEY_ZIP]        NVARCHAR (1000) NULL,
    [SZ_ATTORNEY_FAX]        NVARCHAR (1000) NULL,
    [SZ_SOCIAL_SECURITY_NO]  NVARCHAR (1000) NULL,
    [DT_DOB]                 DATETIME        NULL,
    [SZ_POLICY_HOLDER]       NVARCHAR (1000) NULL,
    [SZ_BILL_NUMBER]         NVARCHAR (255)  NULL,
    [FLT_BILL_AMOUNT]        NVARCHAR (255)  NULL,
    [FLT_PAID]               NVARCHAR (255)  NULL,
    [FLT_BALANCE]            NVARCHAR (255)  NULL,
    [DT_FIRST_VISIT_DATE]    DATETIME        NULL,
    [DT_LAST_VISIT_DATE]     DATETIME        NULL,
    [SZ_CASE_TYPE_NAME]      NVARCHAR (1000) NULL,
    [Location]               NVARCHAR (1000) NULL,
    [SZ_COMPANY_ID]          NVARCHAR (1000) NULL,
    [Company_Name]           NVARCHAR (1000) NULL,
    [Provider_Name]          NVARCHAR (1000) NULL,
    [PROVIDER_ADDRESS]       NVARCHAR (255)  NULL,
    [PROVIDER_CITY]          NVARCHAR (255)  NULL,
    [PROVIDER_ZIP]           NVARCHAR (255)  NULL,
    [PROVIDER_STATE]         NVARCHAR (255)  NULL,
    [DT_DATE_OF_ACCIDENT]    DATETIME        NULL,
    [Verification]           NVARCHAR (2000) NULL,
    [AssignLaw_firm]         NVARCHAR (500)  NULL,
    [Transfer_Amount]        NVARCHAR (255)  NULL,
    [DT_DATE_OF_TRANSFERRED] DATETIME        NULL,
    [BILL_DATE]              DATETIME        NULL,
    [GB_provider_id]         NVARCHAR (255)  NULL,
    [GB_insurancecompanyid]  NVARCHAR (255)  NULL,
    [Denial_Date1]           DATETIME        NULL,
    [Denial_Reason1]         NVARCHAR (500)  NULL,
    [Denial_Date2]           DATETIME        NULL,
    [Denial_Reason2]         NVARCHAR (500)  NULL,
    [Denial_Date3]           DATETIME        NULL,
    [Denial_Reason3]         NVARCHAR (500)  NULL,
    [Denial_Date4]           DATETIME        NULL,
    [Denial_Reason4]         NVARCHAR (500)  NULL,
    [Provider_ID]            NVARCHAR (100)  NULL,
    [InsuranceCompanyId]     NVARCHAR (100)  NULL,
    [Status_Done]            NVARCHAR (50)   NULL,
    [New_Status]             VARCHAR (100)   NULL,
    [DomainId]               NVARCHAR (255)  NULL
);

