CREATE TABLE [dbo].[XN_TEMP_DK] (
    [Provider]            NVARCHAR (255)  NULL,
    [PatientLastName]     NVARCHAR (255)  NULL,
    [PatientFirstName]    NVARCHAR (255)  NULL,
    [Initial_Status]      NVARCHAR (255)  NULL,
    [Status]              NVARCHAR (255)  NULL,
    [InsuranceName]       NVARCHAR (255)  NULL,
    [DateofAccident]      DATETIME        NULL,
    [Claim Number]        NVARCHAR (255)  NULL,
    [PolicyNumber]        NVARCHAR (255)  NULL,
    [BILL_NUMBER]         NVARCHAR (255)  NULL,
    [FltBillAmount]       FLOAT (53)      NULL,
    [Paid_Amount]         FLOAT (53)      NULL,
    [Defendant_Name]      NVARCHAR (255)  NULL,
    [Attorney_Name]       NVARCHAR (255)  NULL,
    [IndexOrAAA_Number]   NVARCHAR (255)  NULL,
    [DateOfService_Start] NVARCHAR (255)  NULL,
    [DateOfService_End]   NVARCHAR (255)  NULL,
    [Date_AAA_Arb_Filed]  NVARCHAR (255)  NULL,
    [AtlasProviderId]     NVARCHAR (255)  NULL,
    [AtlasInsuranceId]    NVARCHAR (255)  NULL,
    [Transferd_Date]      NVARCHAR (255)  NULL,
    [Transferd_Status]    NVARCHAR (255)  NULL,
    [case_code]           FLOAT (53)      NULL,
    [AUTOID]              INT             IDENTITY (1, 1) NOT NULL,
    [DATE_BillSent]       DATETIME        NULL,
    [Deduction]           DECIMAL (18, 2) NULL,
    [Doctor_Name]         VARCHAR (255)   NULL
);

