CREATE TABLE [dbo].[XN_TEMP_Maccolum] (
    [Provider]         NVARCHAR (255) NULL,
    [Patient ID]       NVARCHAR (255) NULL,
    [PatientLastName]  NVARCHAR (255) NULL,
    [PatientFirstName] NVARCHAR (255) NULL,
    [PatientDOB]       NVARCHAR (255) NULL,
    [CaseTypeName]     NVARCHAR (255) NULL,
    [InsuranceName]    NVARCHAR (255) NULL,
    [DateofAccident]   NVARCHAR (255) NULL,
    [Claim Number]     NVARCHAR (255) NULL,
    [PolicyNumber]     NVARCHAR (255) NULL,
    [BillType]         NVARCHAR (255) NULL,
    [TreatingProvider] NVARCHAR (255) NULL,
    [FirstVisitDate]   DATETIME       NULL,
    [LastVisitDate]    DATETIME       NULL,
    [BillDate]         NVARCHAR (255) NULL,
    [FltBillAmount]    FLOAT (53)     NULL,
    [FltPaid]          NVARCHAR (255) NULL,
    [FltBalance]       NVARCHAR (255) NULL,
    [InitialStatus]    NVARCHAR (255) NULL,
    [Notes]            NVARCHAR (255) NULL,
    [ID]               NVARCHAR (255) NULL,
    [DomainId]         NVARCHAR (255) NULL,
    [AtlasProviderId]  NVARCHAR (255) NULL,
    [IsDuplicateCase]  NVARCHAR (255) NULL,
    [AtlasInsuranceId] NVARCHAR (255) NULL,
    [GBB_Type]         NVARCHAR (255) NULL,
    [Transferd_Date]   NVARCHAR (255) NULL,
    [Transferd_Status] NVARCHAR (255) NULL,
    [BILL_NUMBER]      NVARCHAR (255) NULL,
    [SERVICE_TYPE]     NVARCHAR (255) NULL
);

