CREATE TABLE [dbo].[XN_TEMP_McCollum] (
    [Provider]         NVARCHAR (255) NULL,
    [Patient ID]       NVARCHAR (255) NULL,
    [PatientLastName]  NVARCHAR (255) NULL,
    [PatientFirstName] NVARCHAR (255) NULL,
    [PatientDOB]       DATETIME       NULL,
    [CaseTypeName]     NVARCHAR (255) NULL,
    [InsuranceName]    NVARCHAR (255) NULL,
    [DateofAccident]   DATETIME       NULL,
    [Claim Number]     NVARCHAR (255) NULL,
    [PolicyNumber]     NVARCHAR (255) NULL,
    [BillType]         NVARCHAR (255) NULL,
    [TreatingProvider] NVARCHAR (255) NULL,
    [FirstVisitDate]   DATETIME       NULL,
    [LastVisitDate]    DATETIME       NULL,
    [BillDate]         DATETIME       NULL,
    [FltBillAmount]    MONEY          NULL,
    [FltPaid]          MONEY          NULL,
    [FltBalance]       MONEY          NULL,
    [InitialStatus]    NVARCHAR (255) NULL,
    [Notes]            NVARCHAR (255) NULL,
    [ID]               INT            IDENTITY (1, 1) NOT NULL,
    [DomainId]         VARCHAR (500)  NULL,
    [AtlasProviderId]  INT            NULL,
    [IsDuplicateCase]  INT            NULL,
    [AtlasInsuranceId] INT            NULL,
    [GBB_Type]         VARCHAR (10)   NULL,
    [Transferd_Date]   DATE           NULL,
    [Transferd_Status] VARCHAR (100)  NULL
);

