CREATE TABLE [dbo].[XN_TEMP_GBB_ALL_DELETED] (
    [ID]                            INT             NOT NULL,
    [CaseId]                        INT             NOT NULL,
    [CaseNo]                        VARCHAR (500)   NULL,
    [PatientFirstName]              VARCHAR (800)   NULL,
    [PatientLastName]               VARCHAR (800)   NULL,
    [InsuranceName]                 VARCHAR (800)   NULL,
    [InsuranceAddress]              VARCHAR (MAX)   NULL,
    [InsuranceCity]                 VARCHAR (800)   NULL,
    [InsuranceState]                VARCHAR (800)   NULL,
    [InsuranceZip]                  VARCHAR (800)   NULL,
    [InsurancePhone]                VARCHAR (800)   NULL,
    [InsuranceEmail]                VARCHAR (800)   NULL,
    [PatientAddress]                VARCHAR (MAX)   NULL,
    [PatientStreet]                 VARCHAR (800)   NULL,
    [PatientCity]                   VARCHAR (800)   NULL,
    [PatientState]                  VARCHAR (800)   NULL,
    [PatientZip]                    VARCHAR (800)   NULL,
    [PatientPhone]                  VARCHAR (800)   NULL,
    [PolicyNumber]                  VARCHAR (800)   NULL,
    [ClaimNumber]                   VARCHAR (800)   NULL,
    [BillStatusName]                VARCHAR (800)   NULL,
    [AttorneyName]                  VARCHAR (MAX)   NULL,
    [AttorneyLastName]              VARCHAR (800)   NULL,
    [AttorneyAddress]               VARCHAR (MAX)   NULL,
    [AttorneyCity]                  VARCHAR (800)   NULL,
    [AttorneyState]                 VARCHAR (800)   NULL,
    [AttorneyZip]                   VARCHAR (800)   NULL,
    [AttorneyFax]                   VARCHAR (800)   NULL,
    [SocialSecurityNo]              VARCHAR (800)   NULL,
    [PolicyHolder]                  VARCHAR (800)   NULL,
    [BillNumber]                    VARCHAR (800)   NULL,
    [FltBillAmount]                 VARCHAR (800)   NULL,
    [FltPaid]                       VARCHAR (800)   NULL,
    [FltBalance]                    VARCHAR (800)   NULL,
    [FirstVisitDate]                DATETIME        NULL,
    [LastVisitDate]                 DATETIME        NULL,
    [CaseTypeName]                  VARCHAR (800)   NULL,
    [Location]                      VARCHAR (800)   NULL,
    [CompanyId]                     VARCHAR (800)   NULL,
    [CompanyName]                   VARCHAR (800)   NULL,
    [ProviderName]                  VARCHAR (800)   NULL,
    [ProviderAddress]               NVARCHAR (MAX)  NULL,
    [ProviderCity]                  VARCHAR (800)   NULL,
    [ProviderZip]                   VARCHAR (800)   NULL,
    [ProviderState]                 VARCHAR (800)   NULL,
    [ProviderTaxId]                 VARCHAR (800)   NULL,
    [DoctorTaxId]                   VARCHAR (800)   NULL,
    [DoctorName]                    VARCHAR (1000)  NULL,
    [Specialty]                     VARCHAR (800)   NULL,
    [DateofAccident]                DATETIME        NULL,
    [AssignedLawFirmId]             VARCHAR (800)   NULL,
    [TransferAmount]                VARCHAR (800)   NULL,
    [DateOfTransferred]             DATETIME        NULL,
    [BillDate]                      DATETIME        NULL,
    [provider_id]                   VARCHAR (800)   NULL,
    [insurancecompanyid]            VARCHAR (800)   NULL,
    [DenialReason1]                 VARCHAR (8000)  NULL,
    [DenialReason2]                 VARCHAR (8000)  NULL,
    [DenialReason3]                 VARCHAR (8000)  NULL,
    [DomainId]                      VARCHAR (500)   NULL,
    [AtlasProviderId]               INT             NULL,
    [IsDuplicateCase]               INT             NULL,
    [TreatmentDetails]              NVARCHAR (MAX)  NULL,
    [DiagnosisCodes]                NVARCHAR (MAX)  NULL,
    [AtlasInsuranceId]              INT             NULL,
    [GBB_Type]                      VARCHAR (10)    NULL,
    [Transferd_Date]                DATE            NULL,
    [Transferd_Status]              VARCHAR (100)   NULL,
    [AtlasCaseID]                   VARCHAR (40)    NULL,
    [AtlasCaseIndexNumber]          VARCHAR (40)    NULL,
    [AtlasPrincipalAmountCollected] DECIMAL (18, 4) NULL,
    [AtlasInterestAmountCollected]  DECIMAL (18, 4) NULL,
    [AtlasCaseStatus]               VARCHAR (80)    NULL,
    [AtlasLastTransactionDate]      DATETIME        NULL,
    [IsDataSyncedtoGYB]             BIT             NULL,
    [DateSyncedtoGYB]               DATETIME        NULL
);

