CREATE TABLE [dbo].[XN_TEMP_AMT_4] (
    [PatientLastName]         NVARCHAR (255) NULL,
    [PatientFirstName]        NVARCHAR (255) NULL,
    [PatientName]             NVARCHAR (255) NULL,
    [InsuranceName]           NVARCHAR (255) NULL,
    [ClaimNumber]             FLOAT (53)     NULL,
    [FltBillAmount]           FLOAT (53)     NULL,
    [FltPaid]                 FLOAT (53)     NULL,
    [PDF Ledger Balance]      FLOAT (53)     NULL,
    [Last Date of Funding]    FLOAT (53)     NULL,
    [From Excel spreadsheet]  FLOAT (53)     NULL,
    [First DOS of funding]    DATETIME       NULL,
    [Last DOS]                DATETIME       NULL,
    [DateofAccident]          DATETIME       NULL,
    [FirstVisitDate]          DATETIME       NULL,
    [LastVisitDate]           NVARCHAR (255) NULL,
    [Percentage collected ]   FLOAT (53)     NULL,
    [IndexNumber]             NVARCHAR (255) NULL,
    [Provider Attorney]       NVARCHAR (255) NULL,
    [Provider Attorney Phone] NVARCHAR (255) NULL,
    [Albert's Comment]        NVARCHAR (255) NULL,
    [Jason's Comment]         NVARCHAR (255) NULL,
    [1211 Revan's email]      NVARCHAR (255) NULL,
    [Number of CPT procedure] FLOAT (53)     NULL,
    [AtlasInsuranceId]        INT            NULL,
    [AtlasProviderId]         INT            NULL,
    [DomainID]                VARCHAR (50)   NULL,
    [Transferd_Date]          DATE           NULL,
    [Transferd_Status]        VARCHAR (50)   NULL,
    [AUTOID]                  INT            IDENTITY (1, 1) NOT NULL
);

