CREATE TYPE [dbo].[UT_TransferCases] AS TABLE (
    [CaseId]             INT            NOT NULL,
    [CaseNo]             VARCHAR (40)   NULL,
    [PatientFirstName]   VARCHAR (80)   NULL,
    [PatientLastName]    VARCHAR (80)   NULL,
    [InsuranceName]      VARCHAR (200)  NULL,
    [InsuranceAddress]   VARCHAR (80)   NULL,
    [InsuranceCity]      VARCHAR (40)   NULL,
    [InsuranceState]     VARCHAR (40)   NULL,
    [InsuranceZip]       VARCHAR (40)   NULL,
    [InsurancePhone]     VARCHAR (80)   NULL,
    [InsuranceEmail]     VARCHAR (80)   NULL,
    [PatientAddress]     VARCHAR (200)  NULL,
    [PatientStreet]      VARCHAR (80)   NULL,
    [PatientCity]        VARCHAR (80)   NULL,
    [PatientState]       VARCHAR (80)   NULL,
    [PatientZip]         VARCHAR (80)   NULL,
    [PatientPhone]       VARCHAR (80)   NULL,
    [PolicyNumber]       VARCHAR (80)   NULL,
    [ClaimNumber]        VARCHAR (80)   NULL,
    [BillStatusName]     VARCHAR (80)   NULL,
    [AttorneyName]       VARCHAR (80)   NULL,
    [AttorneyLastName]   VARCHAR (80)   NULL,
    [AttorneyAddress]    VARCHAR (200)  NULL,
    [AttorneyCity]       VARCHAR (80)   NULL,
    [AttorneyState]      VARCHAR (80)   NULL,
    [AttorneyZip]        VARCHAR (80)   NULL,
    [AttorneyFax]        VARCHAR (80)   NULL,
    [SocialSecurityNo]   VARCHAR (80)   NULL,
    [PolicyHolder]       VARCHAR (80)   NULL,
    [BillNumber]         VARCHAR (40)   NULL,
    [FltBillAmount]      VARCHAR (40)   NULL,
    [FltPaid]            VARCHAR (40)   NULL,
    [FltBalance]         VARCHAR (40)   NULL,
    [FirstVisitDate]     DATETIME       NULL,
    [LastVisitDate]      DATETIME       NULL,
    [CaseTypeName]       VARCHAR (40)   NULL,
    [Location]           VARCHAR (80)   NULL,
    [CompanyId]          VARCHAR (80)   NULL,
    [CompanyName]        VARCHAR (80)   NULL,
    [ProviderName]       VARCHAR (80)   NULL,
    [ProviderAddress]    VARCHAR (200)  NULL,
    [ProviderCity]       VARCHAR (80)   NULL,
    [ProviderZip]        VARCHAR (80)   NULL,
    [ProviderState]      VARCHAR (80)   NULL,
    [ProviderTaxId]      VARCHAR (80)   NULL,
    [DoctorTaxId]        VARCHAR (80)   NULL,
    [DoctorName]         VARCHAR (80)   NULL,
    [Specialty]          VARCHAR (80)   NULL,
    [DateofAccident]     DATETIME       NULL,
    [AssignedLawFirmId]  VARCHAR (80)   NULL,
    [TransferAmount]     VARCHAR (80)   NULL,
    [DateOfTransferred]  DATETIME       NULL,
    [BillDate]           DATETIME       NULL,
    [provider_id]        VARCHAR (80)   NULL,
    [insurancecompanyid] VARCHAR (80)   NULL,
    [DenialReason1]      VARCHAR (200)  NULL,
    [DenialReason2]      VARCHAR (200)  NULL,
    [DenialReason3]      VARCHAR (200)  NULL,
    [DomainId]           VARCHAR (40)   NULL,
    [AtlasProviderId]    INT            NULL,
    [IsDuplicateCase]    INT            NULL,
    [TreatmentDetails]   NVARCHAR (MAX) NULL,
    [DiagnosisCodes]     NVARCHAR (MAX) NULL,
    [POMStampDate]       DATETIME       NULL,
    [POMGeneratedDate]   DATETIME       NULL,
    [POMId]              VARCHAR (40)   NULL);

