CREATE PROCEDURE [dbo].[SP_DELETE_VERIFICATION_REQUEST]
	@I_VERIFICATION_ID INT
as
begin
	DELETE FROM tbl_verification_response_fax_attachments WHERE I_VERIFICATION_ID = @I_VERIFICATION_ID
	DELETE FROM TXN_VERIFICATION_REQUEST where I_VERIFICATION_ID = @I_VERIFICATION_ID
end

