CREATE PROCEDURE [dbo].[SP_GET_EVENTS_FOR_DATE] --'1/5/2011'
(
	@Event_Date varchar(10)
)
as
begin
	SELECT 
		EVT.CASE_ID [CASE ID],
		EVTTYPE.EVENTTYPENAME[EVENT TYPE],
		EVTSTATUS.EVENTSTATUSNAME [EVENT STATUS], 
		CONVERT(NVARCHAR(11),EVT.EVENT_DATE,101) [EVENT DATE], 
		ISNULL(CONVERT(NVARCHAR(5),EVT.EVENT_TIME,114),'')[EVENT TIME],
		ISNULL(EVT.EVENT_NOTES,'') [EVENT DESCRIPTION],
		EVT.ASSIGNED_TO[ASSIGNED TO],
		PROVIDER_NAME[PROVIDER NAME], 
		ISNULL(vw.InjuredParty_FirstName, N'') + N'  ' + ISNULL(vw.InjuredParty_LastName, N'')    as [INJUREDPARTY NAME], 
		Court_Name[COURT NAME],
		COURT_VENUE[COURT VENUE],
		INDEXORAAA_NUMBER[INDEXORAAA NUMBER],
		DEFENDANT_NAME[DEFENDANT NAME],
		INSURANCECOMPANY_NAME[INSURANCECOMPANY NAME],
		VW.STATUS [STATUS],
		Claim_Amount [CLAIM AMOUNT]
	FROM 
		TBLEVENT EVT with(nolock) JOIN TBLEVENTTYPE EVTTYPE  with(nolock)
		ON EVTTYPE.EVENTTYPEID = EVT.EVENTTYPEID 
		JOIN TBLEVENTSTATUS EVTSTATUS with(nolock)
		ON EVTSTATUS.EVENTSTATUSID = EVT.EVENTSTATUSID 
		JOIN Tblcase  VW with(nolock)
		ON EVT.CASE_ID=VW.CASE_ID 
		INNER JOIN  dbo.tblInsuranceCompany INS WITH (NOLOCK) ON VW.InsuranceCompany_Id = INS.InsuranceCompany_Id 
	    INNER JOIN dbo.tblProvider pro WITH (NOLOCK) ON VW.Provider_Id = pro.Provider_Id
		LEFT OUTER JOIN  dbo.tblDefendant def WITH (NOLOCK) ON vw.Defendant_Id = def.Defendant_id 
		LEFT OUTER JOIN  dbo.tblCourt crt WITH (NOLOCK) ON vw.Court_Id = crt.Court_Id
	WHERE 
		EVT.EVENT_DATE = @EVENT_DATE AND ISNULL(VW.IsDeleted,0) = 0
	ORDER BY 
		Court_Name,
		COURT_VENUE,
		EVT.EVENT_TIME 
end

