CREATE PROCEDURE [dbo].[SP_INSERT_TREATMENT_DOCTOR]
	@DomainId VARCHAR(50),
	@Treatment_Id int,
	@DOCTOR_ID INT 
	
AS
BEGIN
	IF EXISTS(SELECT 1 FROM TXN_CASE_PEER_REVIEW_DOCTOR WHERE TREATMENT_ID=@Treatment_Id AND DOCTOR_ID=@DOCTOR_ID) 
	BEGIN
		RETURN -2
	END
	ELSE
	BEGIN
		INSERT INTO TXN_CASE_PEER_REVIEW_DOCTOR(TREATMENT_ID,DOCTOR_ID,DomainId)
		VALUES(@Treatment_Id,@DOCTOR_ID,@DomainId)
	END
END

