CREATE PROCEDURE [dbo].[SP_RECORD_FOR_RESPONSE] -- 'FH98-mmi-000111'
(
	@SZ_CASE_ID AS NVARCHAR(20)
)
AS
BEGIN
	SELECT TBLPROVIDER.PROVIDER_NAME , 
			INJUREDPARTY_LASTNAME +' '+INJUREDPARTY_FIRSTNAME [INJURED_PARTY],
			ISNULL(INSURANCECOMPANY_SUITNAME,' ') [INSURANCE_COMPANY],
			ISNULL(INDEXORAAA_NUMBER,' ') [INDEXORAAA_NUMBER]
		    FROM TBLCASE,TBLINSURANCECOMPANY,TBLPROVIDER WHERE TBLCASE.CASE_ID = @SZ_CASE_ID
			AND TBLCASE.PROVIDER_ID = TBLPROVIDER.PROVIDER_ID
			AND TBLCASE.INSURANCECOMPANY_ID = TBLINSURANCECOMPANY.INSURANCECOMPANY_ID
END

