CREATE PROCEDURE [dbo].[SpUpdateMergedCasesFilesDetails]
(
	@DOMAINID VARCHAR(20),
	@JOBID INT,
	@FILEPATH VARCHAR(200),
	@PROCESSEDCASES VARCHAR(MAX),
	@NONPROCESSEDCASES VARCHAR(MAX)
)
AS
BEGIN

		UPDATE MergedCasesFiles SET FileName = @FILEPATH, ProcessedCaseId = @PROCESSEDCASES, NonProcessedCaseId = @NONPROCESSEDCASES  WHERE DomainId = @DOMAINID AND JobId = @JOBID

END