CREATE PROCEDURE [dbo].[STP_UID_APPLICATIONSETTING] 
@PARAMETER_ID AS INT,
@PARAMETERVALUE AS VARCHAR(512)

AS 
------------------------------------------------------------------------------------------------------------------
BEGIN
		-- MAINTAINING TRANSACTION
		BEGIN TRANSACTION UPDATE_APPLICATIONSETTING

		UPDATE tblAPPLICATIONSETTINGS
		SET

		PARAMETERVALUE		=   @PARAMETERVALUE
				
		WHERE 	PARAMETERID=@PARAMETER_ID	
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRANSACTION UPDATE_APPLICATIONSETTING
		RAISERROR('AN ERROR HAS OCCURED WHILE SAVING DATA', 16, 1)
		RETURN
	END
	
	COMMIT TRANSACTION UPDATE_APPLICATIONSETTING
END

