CREATE PROCEDURE [dbo].[STP_UID_DELETEIMAGE_NODE]
@NODETYPE CHAR,
@NODEID  INT
AS

BEGIN
	IF @NODETYPE='N'
	BEGIN
		DELETE FROM TBLDOCIMAGES WHERE IMAGEID IN (SELECT IMAGEID FROM TBLIMAGETAG WHERE TAGID=@NODEID)
		DELETE FROM TBLIMAGETAG WHERE TAGID=@NODEID
	END
	ELSE
	BEGIN
		DELETE FROM TBLDOCIMAGES WHERE IMAGEID=@NODEID
		DELETE FROM TBLIMAGETAG WHERE IMAGEID=@NODEID
	END
END

