CREATE PROCEDURE [dbo].[STP_UID_DELETEIMAGE_NODE]
@NODETYPE CHAR,
@NODEID  INT
AS

BEGIN
	IF @NODETYPE='N'
	BEGIN
   ---Start of  changes for LSS-470 done on 5 APRIL 2020  By Tushar Chandgude  
   --DELETE FROM TBLDOCIMAGES WHERE IMAGEID IN (SELECT IMAGEID FROM TBLIMAGETAG WHERE TAGID=@NODEID)    
  --DELETE FROM TBLIMAGETAG WHERE TAGID=@NODEID    
  
   UPDATE TBLDOCIMAGES SET IsDeleted=1 WHERE IMAGEID IN (SELECT IMAGEID FROM TBLIMAGETAG WHERE TAGID=@NODEID) AND IsDeleted=0   
   UPDATE TBLIMAGETAG SET IsDeleted=1  WHERE TAGID=@NODEID  AND IsDeleted=0   
  ---End   of  changes for LSS-470 done on 5 APRIL 2020  By Tushar Chandgude  
	END
	ELSE
	BEGIN
		---Start of  changes for LSS-470 done on 5 APRIL 2020  By Tushar Chandgude  
    --DELETE FROM TBLDOCIMAGES WHERE IMAGEID=@NODEID    
  --DELETE FROM TBLIMAGETAG WHERE IMAGEID=@NODEID    
  
   UPDATE TBLDOCIMAGES  SET IsDeleted=1  WHERE IMAGEID=@NODEID    AND IsDeleted=0   
   UPDATE TBLIMAGETAG  SET IsDeleted=1  WHERE IMAGEID=@NODEID   AND IsDeleted=0   
---End   of  changes for LSS-470 done on 5 APRIL 2020  By Tushar Chandgude  
	END
END

