CREATE PROCEDURE [dbo].[WINAPP_GET_LOGIN_INGO]
	@USER_NAME VARCHAR(8000),
	@PASSWORD VARCHAR(8000)
AS
BEGIN
	SELECT TOP 1 * FROM IssueTracker_Users TU WHERE TU.username=@USER_NAME
		and UserPassword=@PASSWORD
END

